/* Auto-generated by gen_game_ctx.py -- DO NOT EDIT */
/*
 * Stub definitions for EWRAM_DATA globals that have been moved to GameCtx.
 * These satisfy extern declarations in upstream headers for files that
 * have not yet been source-transformed.
 *
 * As more files are transformed, these stubs become less necessary.
 * Eventually, when ALL files are transformed, this file can be removed.
 */

#include "global.h"
#include "gflib.h"
#include "battle.h"
#include "sprite.h"
#include "palette.h"
#include "scanline_effect.h"
#include "link.h"
#include "save.h"
#include "pokemon_storage_system.h"
#include "quest_log.h"
#include "malloc.h"
#include "string_util.h"
#include "trade.h"
#include "field_weather.h"
#include "event_object_movement.h"
#include "overworld.h"
#include "fieldmap.h"
#include "help_system.h"
#include "item.h"
#include "shop.h"
#include "sound.h"
#include "party_menu.h"
#include "window.h"
#include "trainer_card.h"
#include "union_room.h"
#include "battle_controllers.h"
#include "battle_anim.h"
#include "battle_message.h"
#include "item_menu.h"
#include "player_pc.h"
#include "game_ctx_types.h"

/* --- GameCtx: struct definition and g_ctx pointer --- */
#include "game_ctx.h"


__attribute__((weak)) void (*gAnimScriptCallback)(void) = NULL;
__attribute__((weak)) bool8 gAnimScriptActive = 0;
__attribute__((weak)) u8 gAnimVisualTaskCount = 0;
__attribute__((weak)) u8 gAnimSoundTaskCount = 0;
__attribute__((weak)) struct DisableStruct * gAnimDisableStructPtr = NULL;
__attribute__((weak)) s32 gAnimMoveDmg = 0;
__attribute__((weak)) u16 gAnimMovePower = 0;
__attribute__((weak)) u8 gAnimFriendship = 0;
__attribute__((weak)) u16 gWeatherMoveAnim = 0;
__attribute__((weak)) s16 gBattleAnimArgs[ANIM_ARGS_COUNT] = {0};
__attribute__((weak)) u8 gAnimMoveTurn = 0;
__attribute__((weak)) u8 gBattleAnimAttacker = 0;
__attribute__((weak)) u8 gBattleAnimTarget = 0;
__attribute__((weak)) u16 gAnimBattlerSpecies[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gAnimCustomPanning = 0;
__attribute__((weak)) struct UnusedControllerStruct gUnusedControllerStruct = {0};
__attribute__((weak)) u16 gBattle_BG0_X = 0;
__attribute__((weak)) u16 gBattle_BG0_Y = 0;
__attribute__((weak)) u16 gBattle_BG1_X = 0;
__attribute__((weak)) u16 gBattle_BG1_Y = 0;
__attribute__((weak)) u16 gBattle_BG2_X = 0;
__attribute__((weak)) u16 gBattle_BG2_Y = 0;
__attribute__((weak)) u16 gBattle_BG3_X = 0;
__attribute__((weak)) u16 gBattle_BG3_Y = 0;
__attribute__((weak)) u16 gBattle_WIN0H = 0;
__attribute__((weak)) u16 gBattle_WIN0V = 0;
__attribute__((weak)) u16 gBattle_WIN1H = 0;
__attribute__((weak)) u16 gBattle_WIN1V = 0;
__attribute__((weak)) u8 gDisplayedStringBattle[300] = {0};
__attribute__((weak)) u8 gBattleTextBuff1[TEXT_BUFF_ARRAY_COUNT] = {0};
__attribute__((weak)) u8 gBattleTextBuff2[TEXT_BUFF_ARRAY_COUNT] = {0};
__attribute__((weak)) u8 gBattleTextBuff3[TEXT_BUFF_ARRAY_COUNT] = {0};
__attribute__((weak)) u32 gBattleTypeFlags = 0;
__attribute__((weak)) u8 gBattleTerrain = 0;
__attribute__((weak)) u32 gUnusedFirstBattleVar1 = 0;
__attribute__((weak)) struct MultiBattlePokemonTx gMultiPartnerParty[3] = {0};
__attribute__((weak)) u8 * gBattleAnimBgTileBuffer = NULL;
__attribute__((weak)) u8 * gBattleAnimBgTilemapBuffer = NULL;
__attribute__((weak)) u8 gBattleBufferA[MAX_BATTLERS_COUNT][0x200] = {0};
__attribute__((weak)) u8 gBattleBufferB[MAX_BATTLERS_COUNT][0x200] = {0};
__attribute__((weak)) u8 gActiveBattler = 0;
__attribute__((weak)) u32 gBattleControllerExecFlags = 0;
__attribute__((weak)) u8 gBattlersCount = 0;
__attribute__((weak)) u16 gBattlerPartyIndexes[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gBattlerPositions[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gActionsByTurnOrder[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gBattlerByTurnOrder[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gCurrentTurnActionNumber = 0;
__attribute__((weak)) u8 gCurrentActionFuncId = 0;
__attribute__((weak)) struct BattlePokemon gBattleMons[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gBattlerSpriteIds[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gCurrMovePos = 0;
__attribute__((weak)) u8 gChosenMovePos = 0;
__attribute__((weak)) u16 gCurrentMove = 0;
__attribute__((weak)) u16 gChosenMove = 0;
__attribute__((weak)) u16 gCalledMove = 0;
__attribute__((weak)) s32 gBattleMoveDamage = 0;
__attribute__((weak)) s32 gHpDealt = 0;
__attribute__((weak)) s32 gTakenDmg[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u16 gLastUsedItem = 0;
__attribute__((weak)) u8 gLastUsedAbility = 0;
__attribute__((weak)) u8 gBattlerAttacker = 0;
__attribute__((weak)) u8 gBattlerTarget = 0;
__attribute__((weak)) u8 gBattlerFainted = 0;
__attribute__((weak)) u8 gEffectBattler = 0;
__attribute__((weak)) u8 gPotentialItemEffectBattler = 0;
__attribute__((weak)) u8 gAbsentBattlerFlags = 0;
__attribute__((weak)) u8 gCritMultiplier = 0;
__attribute__((weak)) u8 gMultiHitCounter = 0;
__attribute__((weak)) const u8 * gBattlescriptCurrInstr = NULL;
__attribute__((weak)) u32 gUnusedBattleMainVar = 0;
__attribute__((weak)) u8 gChosenActionByBattler[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) const u8 * gSelectionBattleScripts[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u16 gLastPrintedMoves[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u16 gLastMoves[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u16 gLastLandedMoves[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u16 gLastHitByType[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u16 gLastResultingMoves[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u16 gLockedMoves[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gLastHitBy[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u16 gChosenMoveByBattler[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gMoveResultFlags = 0;
__attribute__((weak)) u32 gHitMarker = 0;
__attribute__((weak)) u8 gTakenDmgByBattler[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gUnusedFirstBattleVar2 = 0;
__attribute__((weak)) u16 gSideStatuses[2] = {0};
__attribute__((weak)) struct SideTimer gSideTimers[2] = {0};
__attribute__((weak)) u32 gStatuses3[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) struct DisableStruct gDisableStructs[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u16 gPauseCounterBattle = 0;
__attribute__((weak)) u16 gPaydayMoney = 0;
__attribute__((weak)) u16 gRandomTurnNumber = 0;
__attribute__((weak)) u8 gBattleCommunication[BATTLE_COMMUNICATION_ENTRIES_COUNT] = {0};
__attribute__((weak)) u8 gBattleOutcome = 0;
__attribute__((weak)) struct ProtectStruct gProtectStructs[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) struct SpecialStatus gSpecialStatuses[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u16 gBattleWeather = 0;
__attribute__((weak)) struct WishFutureKnock gWishFutureKnock = {0};
__attribute__((weak)) u16 gIntroSlideFlags = 0;
__attribute__((weak)) u8 gSentPokesToOpponent[2] = {0};
__attribute__((weak)) u16 gDynamicBasePower = 0;
__attribute__((weak)) u16 gExpShareExp = 0;
__attribute__((weak)) struct BattleEnigmaBerry gEnigmaBerries[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) struct BattleScripting gBattleScripting = {0};
__attribute__((weak)) struct BattleStruct * gBattleStruct = NULL;
__attribute__((weak)) u8 * gLinkBattleSendBuffer = NULL;
__attribute__((weak)) u8 * gLinkBattleRecvBuffer = NULL;
__attribute__((weak)) struct BattleResources * gBattleResources = NULL;
__attribute__((weak)) u8 gActionSelectionCursor[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gMoveSelectionCursor[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gBattlerStatusSummaryTaskId[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u8 gBattlerInMenuId = 0;
__attribute__((weak)) bool8 gDoingBattleAnim = 0;
__attribute__((weak)) u32 gTransformedPersonalities[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) struct BattleSpriteData * gBattleSpritesDataPtr = NULL;
__attribute__((weak)) struct MonSpritesGfx * gMonSpritesGfxPtr = NULL;
__attribute__((weak)) u16 gBattleMovePower = 0;
__attribute__((weak)) u16 gMoveToLearn = 0;
__attribute__((weak)) u8 gBattleMonForms[MAX_BATTLERS_COUNT] = {0};
__attribute__((weak)) u16 gTrainerBattleOpponent_A = 0;
__attribute__((weak)) bool8 gHasHallOfFameRecords = 0;
__attribute__((weak)) u16 gSpecialVar_0x8000 = 0;
__attribute__((weak)) u16 gSpecialVar_0x8001 = 0;
__attribute__((weak)) u16 gSpecialVar_0x8002 = 0;
__attribute__((weak)) u16 gSpecialVar_0x8003 = 0;
__attribute__((weak)) u16 gSpecialVar_0x8004 = 0;
__attribute__((weak)) u16 gSpecialVar_0x8005 = 0;
__attribute__((weak)) u16 gSpecialVar_0x8006 = 0;
__attribute__((weak)) u16 gSpecialVar_0x8007 = 0;
__attribute__((weak)) u16 gSpecialVar_0x8008 = 0;
__attribute__((weak)) u16 gSpecialVar_0x8009 = 0;
__attribute__((weak)) u16 gSpecialVar_0x800A = 0;
__attribute__((weak)) u16 gSpecialVar_0x800B = 0;
__attribute__((weak)) u16 gSpecialVar_Result = 0;
__attribute__((weak)) u16 gSpecialVar_LastTalked = 0;
__attribute__((weak)) u16 gSpecialVar_Facing = 0;
__attribute__((weak)) u16 gSpecialVar_MonBoxId = 0;
__attribute__((weak)) u16 gSpecialVar_MonBoxPos = 0;
__attribute__((weak)) u16 gSpecialVar_TextColor = 0;
__attribute__((weak)) u16 gSpecialVar_PrevTextColor = 0;
__attribute__((weak)) u16 gSpecialVar_0x8014 = 0;
__attribute__((weak)) u8 sSpecialFlags[SPECIAL_FLAGS_SIZE] = {0};
__attribute__((weak)) u8 sCurrentReflectionType = 0;
__attribute__((weak)) u16 sCurrentSpecialObjectPaletteTag = 0;
__attribute__((weak)) bool8 gBikeCameraAheadPanback = 0;
__attribute__((weak)) u32 gFieldEffectArguments[8] = {0};
__attribute__((weak)) struct ObjectEvent gObjectEvents[OBJECT_EVENTS_COUNT] = {0};
__attribute__((weak)) struct PlayerAvatar gPlayerAvatar = {0};
__attribute__((weak)) u16 gBackupMapData[VIRTUAL_MAP_SIZE] = {0};
__attribute__((weak)) struct MapHeader gMapHeader = {0};
__attribute__((weak)) struct Camera gCamera = {0};
__attribute__((weak)) u8 gGlobalFieldTintMode = 0;
__attribute__((weak)) struct MapPosition gPlayerFacingPosition = {0};
__attribute__((weak)) u8 gDisableHelpSystemVolumeReduce = 0;
__attribute__((weak)) bool8 gHelpSystemToggleWithRButtonDisabled = 0;
__attribute__((weak)) struct HelpSystemListMenu gHelpSystemListMenu = {0};
__attribute__((weak)) struct ListMenuItem gHelpSystemListMenuItems[52] = {0};
__attribute__((weak)) struct BagPocket gBagPockets[NUM_BAG_POCKETS] = {0};
__attribute__((weak)) struct BagStruct gBagMenuState = {0};
__attribute__((weak)) u16 gSpecialVar_ItemId = 0;
/* SKIP anon struct: sLinkErrorBuffer */
__attribute__((weak)) u32 gBerryBlenderKeySendAttempts = 0;
__attribute__((weak)) u16 gBlockRecvBuffer[MAX_RFU_PLAYERS][BLOCK_BUFFER_SIZE / 2] = {0};
__attribute__((weak)) u8 gBlockSendBuffer[BLOCK_BUFFER_SIZE] = {0};
__attribute__((weak)) u16 gLinkType = 0;
__attribute__((weak)) struct LinkPlayer gLocalLinkPlayer = {0};
__attribute__((weak)) struct LinkPlayer gLinkPlayers[MAX_RFU_PLAYERS] = {0};
__attribute__((weak)) struct LinkPlayer gSavedLinkPlayers[MAX_RFU_PLAYERS] = {0};
__attribute__((weak)) struct SaveBlock2 gSaveBlock2 = {0};
__attribute__((weak)) u8 gSaveBlock2_DMA[SAVEBLOCK_MOVE_RANGE] = {0};
__attribute__((weak)) struct SaveBlock1 gSaveBlock1 = {0};
__attribute__((weak)) u8 gSaveBlock1_DMA[SAVEBLOCK_MOVE_RANGE] = {0};
__attribute__((weak)) struct PokemonStorage gPokemonStorage = {0};
__attribute__((weak)) u8 gSaveBlock3_DMA[SAVEBLOCK_MOVE_RANGE] = {0};
__attribute__((weak)) struct LoadedSaveData gLoadedSaveData = {0};
__attribute__((weak)) u32 gLastEncryptionKey = 0;
__attribute__((weak)) u8 gDecompressionBuffer[0x4000] = {0};
__attribute__((weak)) u16 gTrainerId = 0;
__attribute__((weak)) u8 sDownArrowCounterAndYCoordIdx[8] = {0};
__attribute__((weak)) bool8 gGiftIsFromEReader = 0;
__attribute__((weak)) bool8 gDifferentSaveFile = 0;
__attribute__((weak)) struct WarpData gLastUsedWarp = {0};
__attribute__((weak)) bool8 gDisableMapMusicChangeOnMapLoad = 0;
__attribute__((weak)) bool8 gExitStairsMovementDisabled = 0;
__attribute__((weak)) struct LinkPlayerObjectEvent gLinkPlayerObjectEvents[4] = {0};
__attribute__((weak)) u16 gPlttBufferUnfaded[PLTT_BUFFER_SIZE] = {0};
__attribute__((weak)) u16 gPlttBufferFaded[PLTT_BUFFER_SIZE] = {0};
__attribute__((weak)) struct PaletteFadeControl gPaletteFade = {0};
__attribute__((weak)) u8 gPaletteDecompressionBuffer[PLTT_SIZE] = {0};
__attribute__((weak)) struct PartyMenu gPartyMenu = {0};
__attribute__((weak)) bool8 gPartyMenuUseExitCallback = 0;
__attribute__((weak)) u8 gSelectedMonPartyId = 0;
__attribute__((weak)) MainCallback gPostMenuFieldCallback = 0;
__attribute__((weak)) u8 gSelectedOrderFromParty[3] = {0};
__attribute__((weak)) u8 gBattlePartyCurrentOrder[PARTY_SIZE / 2] = {0};
__attribute__((weak)) struct PlayerPCItemPageStruct gPlayerPcMenuManager = {0};
__attribute__((weak)) u8 gPlayerPartyCount = 0;
__attribute__((weak)) u8 gEnemyPartyCount = 0;
__attribute__((weak)) struct Pokemon gEnemyParty[PARTY_SIZE] = {0};
__attribute__((weak)) struct Pokemon gPlayerParty[PARTY_SIZE] = {0};
__attribute__((weak)) struct SpriteTemplate gMultiuseSpriteTemplate = {0};
__attribute__((weak)) struct PokemonStorageSystemData * gStorage = NULL;
__attribute__((weak)) u8 gQuestLogState = 0;
__attribute__((weak)) u16 * gQuestLogDefeatedWildMonRecord = NULL;
__attribute__((weak)) u16 * gQuestLogRecordingPointer = NULL;
__attribute__((weak)) u16 gQuestLogCurActionIdx = 0;
__attribute__((weak)) struct QuestLogRepeatEventTracker gQuestLogRepeatEventTracker = {0};
__attribute__((weak)) u8 sLocationHistory[3][2] = {0};
__attribute__((weak)) u8 sRoamerLocation[2] = {0};
__attribute__((weak)) u8 gNumSafariBalls = 0;
__attribute__((weak)) u16 gSafariZoneStepCounter = 0;
__attribute__((weak)) struct SaveSector gSaveDataBuffer = {0};
__attribute__((weak)) u32 gSaveUnusedVar2 = 0;
__attribute__((weak)) u16 gScanlineEffectRegBuffers[2][0x3C0] = {0};
__attribute__((weak)) struct ScanlineEffect gScanlineEffect = {0};
__attribute__((weak)) u8 gWalkAwayFromSignInhibitTimer = 0;
__attribute__((weak)) const u8 * gRamScriptRetAddr = NULL;
__attribute__((weak)) u16 (*gShopTilemapBuffer1)[0x400] = NULL;
__attribute__((weak)) u16 (*gShopTilemapBuffer2)[0x400] = NULL;
__attribute__((weak)) u16 (*gShopTilemapBuffer3)[0x400] = NULL;
__attribute__((weak)) u16 (*gShopTilemapBuffer4)[0x400] = NULL;
__attribute__((weak)) struct ListMenuItem * sShopMenuListMenu = NULL;
__attribute__((weak)) struct QuestLogEvent_Shop sHistory[2] = {0};
__attribute__((weak)) struct MusicPlayerInfo * gMPlay_PokemonCry = NULL;
__attribute__((weak)) u8 gPokemonCryBGMDuckingCounter = 0;
__attribute__((weak)) struct Sprite gSprites[MAX_SPRITES + 1] = {0};
__attribute__((weak)) u16 gSpritePriorities[MAX_SPRITES] = {0};
__attribute__((weak)) u8 gSpriteOrder[MAX_SPRITES] = {0};
__attribute__((weak)) bool8 gShouldProcessSpriteCopyRequests = 0;
__attribute__((weak)) u8 gSpriteCopyRequestCount = 0;
__attribute__((weak)) struct SpriteCopyRequest gSpriteCopyRequests[MAX_SPRITES] = {0};
__attribute__((weak)) u8 gOamLimit = 0;
__attribute__((weak)) u16 gReservedSpriteTileCount = 0;
__attribute__((weak)) u8 gSpriteTileAllocBitmap[128] = {0};
__attribute__((weak)) s16 gSpriteCoordOffsetX = 0;
__attribute__((weak)) s16 gSpriteCoordOffsetY = 0;
__attribute__((weak)) struct OamMatrix gOamMatrices[OAM_MATRIX_COUNT] = {0};
__attribute__((weak)) bool8 gAffineAnimsDisabled = 0;
__attribute__((weak)) u8 gStringVar1[32] = {0};
__attribute__((weak)) u8 gStringVar2[20] = {0};
__attribute__((weak)) u8 gStringVar3[20] = {0};
__attribute__((weak)) u8 gStringVar4[1000] = {0};
__attribute__((weak)) u8 gUnknownStringVar[16] = {0};
__attribute__((weak)) struct Mail gLinkPartnerMail[PARTY_SIZE] = {0};
__attribute__((weak)) u8 gSelectedTradeMonPositions[2] = {0};
__attribute__((weak)) struct TrainerCard gTrainerCards[4] = {0};
__attribute__((weak)) struct RfuGameCompatibilityData gRfuPartnerCompatibilityData = {0};
__attribute__((weak)) u16 gUnionRoomOfferedSpecies = 0;
__attribute__((weak)) u8 gUnionRoomRequestedMonType = 0;
__attribute__((weak)) struct Window gWindows[WINDOWS_MAX] = {0};
__attribute__((weak)) u8 gHeap[HEAP_SIZE] = {0};
