#!/usr/bin/env python3
"""
Generate host-native battle animation pointer tables.

The upstream battle animation script file stores jump tables as `.4byte`
entries, which are 32-bit GBA pointers and therefore unusable as-is on the
native 64-bit build. This tool parses those table sections and emits real C
pointer arrays that reference the host-native script labels generated by
`tools/script_assembler.py`.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


TABLES = (
    "gBattleAnims_Moves",
    "gBattleAnims_StatusConditions",
    "gBattleAnims_General",
    "gBattleAnims_Special",
)


LABEL_RE = re.compile(r"^([A-Za-z_]\w*)::\s*$")
ENTRY_RE = re.compile(r"^\.4byte\s+([A-Za-z_]\w*)\s*$")


def parse_tables(source: Path) -> dict[str, list[str]]:
    tables = {name: [] for name in TABLES}
    current: str | None = None

    for raw_line in source.read_text().splitlines():
        line = raw_line.split("@", 1)[0].strip()
        if not line:
            continue

        label_match = LABEL_RE.match(line)
        if label_match:
            label = label_match.group(1)
            current = label if label in tables else None
            continue

        if current is None:
            continue

        entry_match = ENTRY_RE.match(line)
        if entry_match:
            tables[current].append(entry_match.group(1))
            continue

        if line.startswith(".align"):
            continue

        current = None

    missing = [name for name, entries in tables.items() if not entries]
    if missing:
        raise ValueError(f"Failed to parse battle animation tables: {', '.join(missing)}")
    return tables


def emit_table(handle, name: str, entries: list[str]) -> None:
    handle.write(f"const u8 *const {name}[] = {{\n")
    for entry in entries:
        handle.write(f"    {entry},\n")
    handle.write("};\n")
    handle.write(f'_Static_assert(ARRAY_COUNT({name}) == {len(entries)}, "{name} size mismatch");\n\n')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Path to data/battle_anim_scripts.s")
    parser.add_argument("--output", required=True, help="Output C file")
    parser.add_argument(
        "--header",
        default="upstream_battle_anim_scripts.h",
        help="Header declaring generated script labels",
    )
    args = parser.parse_args()

    source = Path(args.input).resolve()
    output = Path(args.output).resolve()
    tables = parse_tables(source)

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w") as handle:
        handle.write("/*\n")
        handle.write(" * Auto-generated by tools/battle_anim_tables_to_c.py\n")
        handle.write(" * DO NOT EDIT — regenerate from upstream data/battle_anim_scripts.s.\n")
        handle.write(" */\n\n")
        handle.write('#include "global.h"\n')
        handle.write(f'#include "{args.header}"\n\n')
        for name in TABLES:
            emit_table(handle, name, tables[name])


if __name__ == "__main__":
    main()
