#!/usr/bin/env python3
"""
extract_incbin.py — INCBIN dependency extractor for pokefirered-native.

Scans upstream C files for INCBIN_* macros and emits a deterministic asset
manifest that can drive the native asset pipeline without hand-maintained
conversion tables.

Usage:
    python3 tools/extract_incbin.py src/text.c src/new_menu_helpers.c \
        --upstream-root third_party/pokefirered \
        [--output-format list|cmake|batch]

    python3 tools/extract_incbin.py emit-manifest \
        third_party/pokefirered/src/intro.c \
        third_party/pokefirered/src/title_screen.c \
        --upstream-root third_party/pokefirered \
        --output .project/assets/boot_path.manifest

    python3 tools/extract_incbin.py verify-manifest \
        .project/assets/boot_path.manifest \
        --upstream-root third_party/pokefirered
"""

import argparse
import os
import re
import sys
from collections import defaultdict

INCBIN_PATTERN = re.compile(
    r'INCBIN_([US])(\d+)\s*\(\s*"([^"]+)"\s*\)'
)

MANIFEST_HEADER = "# pfr_asset_manifest v1"


def extract_incbins(filepath):
    """Extract all INCBIN asset paths from a C source file."""
    results = []
    with open(filepath, "r", encoding="utf-8") as f:
        for lineno, line in enumerate(f, 1):
            for match in INCBIN_PATTERN.finditer(line):
                sign = match.group(1).lower()
                width = match.group(2)
                asset_path = match.group(3)
                results.append({
                    "path": asset_path,
                    "type": f"{sign}{width}",
                    "file": filepath,
                    "line": lineno,
                })
    return results


def strip_graphics_prefix(path):
    """Strip leading 'graphics/' prefix used in INCBIN macros."""
    if path.startswith("graphics/"):
        return path[len("graphics/"):]
    return path


def normalize_source_path(path, upstream_root):
    try:
        return os.path.relpath(path, upstream_root)
    except ValueError:
        return path


def canonicalize_assets(assets):
    grouped = defaultdict(set)
    for asset in assets:
        grouped[asset["path"]].add(asset["type"])

    rows = []
    for path in sorted(grouped):
        rows.append({
            "path": path,
            "types": sorted(grouped[path]),
        })
    return rows


def check_exists(asset_path, upstream_root):
    """Check if the referenced asset file exists in the upstream tree."""
    full_path = os.path.join(upstream_root, asset_path)
    return os.path.exists(full_path)


def format_list(assets, upstream_root):
    """Plain text list output."""
    lines = []
    for asset in canonicalize_assets(assets):
        exists = check_exists(asset["path"], upstream_root)
        status = "OK" if exists else "MISSING"
        lines.append(
            f"  {asset['path']}  ({','.join(asset['types'])})  [{status}]"
        )
    return "\n".join(lines)


def format_cmake(assets, upstream_root):
    """CMake file(COPY) rules output."""
    lines = ["# Auto-generated by extract_incbin.py", ""]
    for asset in canonicalize_assets(assets):
        src = os.path.join("${POKEFIRERED_SOURCE_DIR}", asset["path"])
        stripped = strip_graphics_prefix(asset["path"])
        dest_dir = os.path.join("${PFR_ASSETS_DIR}", os.path.dirname(stripped))
        lines.append(f"file(COPY {src} DESTINATION {dest_dir})")
    return "\n".join(lines)


def classify_asset(asset_path):
    ext = os.path.splitext(asset_path)[1]
    if ext in (".png",):
        return "CONVERT (upstream make / gbagfx)"
    if ext in (".pal",):
        return "CONVERT (upstream make / gbagfx)"
    return "COPY OR BUILD EXACT INCBIN"


def format_batch(assets, upstream_root):
    """Show which assets need canonical upstream materialization."""
    lines = ["# Assets needed by the canonical asset pipeline", ""]
    for asset in canonicalize_assets(assets):
        exists = check_exists(asset["path"], upstream_root)
        status = "OK" if exists else "BUILD"
        lines.append(
            f"  {asset['path']}  ({','.join(asset['types'])})"
            f"  → {classify_asset(asset['path'])}  [{status}]"
        )
    return "\n".join(lines)


def build_manifest_text(files, upstream_root, assets):
    rows = canonicalize_assets(assets)
    lines = [
        MANIFEST_HEADER,
        "# Relative to upstream root; second field is the union of INCBIN element types.",
    ]
    for path in files:
        lines.append(
            f"# source: {normalize_source_path(path, upstream_root)}"
        )
    lines.append("")
    for row in rows:
        lines.append(f"{row['path']} {'/'.join(row['types'])}")
    lines.append("")
    return "\n".join(lines)


def parse_manifest(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            if line == MANIFEST_HEADER:
                continue
            parts = line.split()
            if len(parts) != 2:
                raise ValueError(f"Malformed manifest line in {path}: {raw.rstrip()}")
            rows.append((parts[0], parts[1]))
    rows.sort()
    return rows


def emit_manifest(files, upstream_root, output):
    assets = []
    for filepath in files:
        if not os.path.exists(filepath):
            raise FileNotFoundError(filepath)
        assets.extend(extract_incbins(filepath))

    manifest_text = build_manifest_text(files, upstream_root, assets)
    output_dir = os.path.dirname(output)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    with open(output, "w", encoding="utf-8") as f:
        f.write(manifest_text)
    print(f"Wrote manifest: {output}", file=sys.stderr)


def verify_manifest(manifest_path, upstream_root):
    with open(manifest_path, "r", encoding="utf-8") as f:
        source_files = []
        for raw in f:
            line = raw.rstrip("\n")
            if line.startswith("# source: "):
                rel_path = line[len("# source: "):].strip()
                source_files.append(os.path.join(upstream_root, rel_path))

    if not source_files:
        raise ValueError(f"No '# source:' entries found in {manifest_path}")

    generated_assets = []
    for path in source_files:
        if not os.path.exists(path):
            raise FileNotFoundError(path)
        generated_assets.extend(extract_incbins(path))

    expected = []
    for row in canonicalize_assets(generated_assets):
        expected.append((row["path"], "/".join(row["types"])))
    expected.sort()

    actual = parse_manifest(manifest_path)
    if actual != expected:
        print(f"Manifest mismatch: {manifest_path}", file=sys.stderr)
        print("Expected:", file=sys.stderr)
        for path, types in expected:
            print(f"  {path} {types}", file=sys.stderr)
        print("Actual:", file=sys.stderr)
        for path, types in actual:
            print(f"  {path} {types}", file=sys.stderr)
        return 1

    print(f"Manifest OK: {manifest_path}", file=sys.stderr)
    return 0


def legacy_main(argv):
    parser = argparse.ArgumentParser(
        description="Extract INCBIN dependencies from upstream C files"
    )
    parser.add_argument("files", nargs="+", help="C source files to scan")
    parser.add_argument(
        "--upstream-root",
        default="third_party/pokefirered",
        help="Path to upstream pokefirered root",
    )
    parser.add_argument(
        "--output-format",
        choices=["list", "cmake", "batch"],
        default="list",
        help="Output format",
    )
    args = parser.parse_args(argv)

    all_assets = []
    for filepath in args.files:
        if not os.path.exists(filepath):
            print(f"Warning: {filepath} not found", file=sys.stderr)
            continue
        assets = extract_incbins(filepath)
        all_assets.extend(assets)
        print(f"# {filepath}: {len(assets)} INCBIN references", file=sys.stderr)

    if not all_assets:
        print("No INCBIN references found.", file=sys.stderr)
        return 1

    unique_paths = sorted(set(a["path"] for a in all_assets))
    print(
        f"# Total: {len(all_assets)} references, {len(unique_paths)} unique assets",
        file=sys.stderr,
    )

    if args.output_format == "list":
        print(format_list(all_assets, args.upstream_root))
    elif args.output_format == "cmake":
        print(format_cmake(all_assets, args.upstream_root))
    else:
        print(format_batch(all_assets, args.upstream_root))
    return 0


def main():
    if len(sys.argv) > 1 and sys.argv[1] in ("emit-manifest", "verify-manifest"):
        parser = argparse.ArgumentParser(description="Manage deterministic asset manifests")
        subparsers = parser.add_subparsers(dest="cmd", required=True)

        emit = subparsers.add_parser("emit-manifest")
        emit.add_argument("files", nargs="+", help="C source files to scan")
        emit.add_argument(
            "--upstream-root",
            default="third_party/pokefirered",
            help="Path to upstream pokefirered root",
        )
        emit.add_argument("--output", required=True, help="Manifest output path")

        verify = subparsers.add_parser("verify-manifest")
        verify.add_argument("manifest", help="Manifest to verify")
        verify.add_argument(
            "--upstream-root",
            default="third_party/pokefirered",
            help="Path to upstream pokefirered root",
        )

        args = parser.parse_args()
        if args.cmd == "emit-manifest":
            emit_manifest(args.files, args.upstream_root, args.output)
            return 0
        return verify_manifest(args.manifest, args.upstream_root)

    return legacy_main(sys.argv[1:])


if __name__ == "__main__":
    raise SystemExit(main())
