#!/usr/bin/env python3
"""Inject game_ctx.h and game_ctx_macros.h includes into generated .c files.

Skips files that:
- Already have game_ctx_macros.h
- Were transformed by gen_game_ctx.py (GameCtx-transformed marker)
- Were generated by gen_game_ctx.py (gen_game_ctx.py marker, e.g. stubs)
- Have no #include "*.h" lines (data-only files)
"""

import os
import re
import sys

INJECTION_BLOCK = (
    '\n'
    '/* --- GameCtx: struct definition and g_ctx pointer --- */\n'
    '#include "game_ctx.h"\n'
    '#include "game_ctx_macros.h"\n'
)

MARKER = '#include "game_ctx_macros.h"'
SKIP_MARKERS = ['GameCtx-transformed', 'gen_game_ctx.py']

HEADER_INCLUDE_RE = re.compile(r'^\s*#\s*include\s+[<"].*\.h[>"]')


def inject_file(filepath):
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        lines = f.readlines()

    for line in lines:
        if MARKER in line:
            return False

    last_include_idx = -1
    for i, line in enumerate(lines):
        if HEADER_INCLUDE_RE.match(line):
            last_include_idx = i

    if last_include_idx < 0:
        return False

    lines.insert(last_include_idx + 1, INJECTION_BLOCK)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.writelines(lines)
    return True


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <gen-dir>", file=sys.stderr)
        sys.exit(1)

    gen_dir = sys.argv[1]
    patched = 0
    skipped_already = 0
    skipped_transformed = 0
    skipped_no_includes = 0

    for name in sorted(os.listdir(gen_dir)):
        if not name.endswith('.c'):
            continue
        filepath = os.path.join(gen_dir, name)
        if not os.path.isfile(filepath):
            continue

        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read()

        if MARKER in content:
            skipped_already += 1
            continue

        if any(m in content for m in SKIP_MARKERS):
            skipped_transformed += 1
            continue

        has_header_include = False
        for line in content.splitlines():
            if HEADER_INCLUDE_RE.match(line):
                has_header_include = True
                break

        if not has_header_include:
            skipped_no_includes += 1
            continue

        if inject_file(filepath):
            patched += 1

    print(f"Done: {patched} patched, {skipped_already} already had macros, "
          f"{skipped_transformed} already transformed, "
          f"{skipped_no_includes} no header includes")


if __name__ == '__main__':
    main()
