#!/usr/bin/env python3
"""
Generate a native `gSpecials` table from upstream `data/specials.inc`.

The upstream table is a `.4byte` array of function pointers. On the native
build this must be emitted as a real host pointer array, plus a correct
one-past-end symbol for the script command bounds check.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


HOST_PTR_BYTES = 8
ASM_ALIAS_PREFIX = "pfr_sp_ext_"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Path to data/specials.inc")
    parser.add_argument("--output", required=True, help="Output C file")
    args = parser.parse_args()

    source = Path(args.input).resolve()
    output = Path(args.output).resolve()
    entries: list[str] = []

    pattern = re.compile(r"^\s*def_special\s+([A-Za-z_]\w*)")
    for line in source.read_text().splitlines():
        match = pattern.match(line)
        if match:
            entries.append(match.group(1))

    unique_entries = []
    seen = set()
    for entry in entries:
        if entry not in seen:
            unique_entries.append(entry)
            seen.add(entry)

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w") as handle:
        handle.write("/*\n")
        handle.write(" * Auto-generated by tools/specials_to_c.py\n")
        handle.write(" * DO NOT EDIT — regenerate from upstream data/specials.inc.\n")
        handle.write(" */\n\n")
        handle.write('#include "global.h"\n\n')
        handle.write(f"#define HOST_PTR_BYTES {HOST_PTR_BYTES}\n")
        handle.write('_Static_assert(sizeof(void *) == HOST_PTR_BYTES, "native specials table expects 64-bit pointers");\n\n')
        handle.write("/* Create host-visible aliases without redeclaring the callbacks' true C prototypes. */\n")
        handle.write("__asm__(\n")
        for entry in unique_entries:
            handle.write(f'    ".global {ASM_ALIAS_PREFIX}{entry}\\n\\t"\n')
            handle.write(f'    "{ASM_ALIAS_PREFIX}{entry} = {entry}\\n\\t"\n')
        handle.write(");\n\n")
        for entry in unique_entries:
            handle.write(f"extern u8 {ASM_ALIAS_PREFIX}{entry}[];\n")
        handle.write("\n")
        handle.write("u16 (*const gSpecials[])(void) = {\n")
        for entry in entries:
            handle.write(f"    (u16 (*)(void)){ASM_ALIAS_PREFIX}{entry},\n")
        handle.write("};\n\n")
        handle.write(f"_Static_assert(ARRAY_COUNT(gSpecials) == {len(entries)}, \"gSpecials size mismatch\");\n")
        handle.write("__asm__(\n")
        handle.write('    ".global gSpecialsEnd\\n\\t"\n')
        handle.write(f'    "gSpecialsEnd = gSpecials + {len(entries) * HOST_PTR_BYTES}\\n\\t"\n')
        handle.write(");\n")


if __name__ == "__main__":
    main()
