#ifndef POKEFIRERED_NATIVE_HOST_TITLE_SCREEN_STUBS_H
#define POKEFIRERED_NATIVE_HOST_TITLE_SCREEN_STUBS_H

#include "global.h"

extern u32 gHostTitleStubSetHelpContextCalls;
extern u32 gHostTitleStubHelpSystemEnableCalls;
extern u32 gHostTitleStubHelpSystemDisableCalls;
extern u32 gHostTitleStubM4aMPlayAllStopCalls;
extern u32 gHostTitleStubCB2InitMainMenuCalls;
extern u32 gHostTitleStubCB2InitBerryFixProgramCalls;
extern u32 gHostTitleStubLoadStdWindowGfxCalls;
extern u32 gHostTitleStubDrawStdFrameCalls;
extern u32 gHostTitleStubAddTextPrinterParameterized4Calls;
extern u32 gHostTitleStubCreateYesNoMenuCalls;
extern u32 gHostTitleStubMenuProcessInputCalls;
extern u32 gHostTitleStubDestroyYesNoMenuCalls;
extern u32 gHostTitleStubDeactivateAllTextPrintersCalls;
extern u32 gHostTitleStubMultiBootInitCalls;
extern u32 gHostTitleStubMultiBootMainCalls;
extern u32 gHostTitleStubMultiBootStartMasterCalls;
extern u32 gHostTitleStubMultiBootCheckCompleteCalls;
extern u32 gHostTitleStubAddTextPrinterParameterized3Calls;
extern u32 gHostTitleStubLoadBgTilesCalls;
extern u32 gHostTitleStubFillBgTilemapBufferRectCalls;
extern u32 gHostTitleStubRunTextPrintersCalls;
extern u32 gHostTitleStubIsTextPrinterActiveCalls;
extern u32 gHostTitleStubFreeAllSpritePalettesCalls;
extern u32 gHostTitleStubStartNewGameSceneCalls;
extern u32 gHostTitleStubCB2InitMysteryGiftCalls;
extern u32 gHostTitleStubIsWirelessAdapterConnectedCalls;
extern u32 gHostTitleStubIsMysteryGiftEnabledCalls;
extern u32 gHostTitleStubFlagGetCalls;
extern u32 gHostTitleStubGetNationalPokedexCountCalls;
extern u32 gHostTitleStubGetKantoPokedexCountCalls;
extern int gHostTitleStubLastMultiBootLength;
extern u8 gHostTitleStubLastHelpContext;
extern const u8 *gHostTitleStubLastPrintedText3;
extern u32 gHostTitleStubWirelessAdapterConnected;
extern bool32 gHostTitleStubMysteryGiftEnabled;
extern u32 gHostTitleStubNationalPokedexEnabled;
extern u32 gHostTitleStubNationalPokedexCount;
extern u32 gHostTitleStubKantoPokedexCount;
extern u32 gHostTitleStubFlagGetBadgeMask;
extern u32 gHostTitleStubTextPrinterActive;
extern const u8 *gHostTitleStubLastPrintedText;
extern s32 gHostTitleStubMenuProcessInputResult;

void HostTitleScreenStubReset(void);
void HostTitleScreenStubSetMenuProcessInputResult(s8 result);
u8 HostTitleScreenStubInitMenuCursor(u8 windowId, u8 left, u8 top, u8 cursorHeight, u8 numChoices, u8 initialCursorPos);
s8 HostTitleScreenStubProcessMenuInput(bool8 wrapAround);
void HostTitleScreenStubForgetMenuWindow(u8 windowId);

#endif
