#ifndef POKEFIRERED_NATIVE_HOST_TITLE_SCREEN_STUBS_H
#define POKEFIRERED_NATIVE_HOST_TITLE_SCREEN_STUBS_H

#include "global.h"

extern u32 gHostTitleStubSetHelpContextCalls;
extern u32 gHostTitleStubHelpSystemEnableCalls;
extern u32 gHostTitleStubHelpSystemDisableCalls;
extern u32 gHostTitleStubFadeOutMapMusicCalls;
extern u32 gHostTitleStubFadeOutBGMCalls;
extern u32 gHostTitleStubIsNotWaitingForBGMStopCalls;
extern u32 gHostTitleStubPlayCryNormalCalls;
extern u32 gHostTitleStubM4aMPlayAllStopCalls;
extern u32 gHostTitleStubSetSaveBlocksPointersCalls;
extern u32 gHostTitleStubCB2InitMainMenuCalls;
extern u32 gHostTitleStubCB2InitBerryFixProgramCalls;
extern u32 gHostTitleStubLoadStdWindowGfxCalls;
extern u32 gHostTitleStubDrawStdFrameCalls;
extern u32 gHostTitleStubAddTextPrinterParameterized4Calls;
extern u32 gHostTitleStubCreateYesNoMenuCalls;
extern u32 gHostTitleStubMenuProcessInputCalls;
extern u32 gHostTitleStubDestroyYesNoMenuCalls;
extern u32 gHostTitleStubFreeAllWindowBuffersCalls;
extern u32 gHostTitleStubDeactivateAllTextPrintersCalls;
extern u32 gHostTitleStubClearSaveDataCalls;
extern u32 gHostTitleStubMultiBootInitCalls;
extern u32 gHostTitleStubMultiBootMainCalls;
extern u32 gHostTitleStubMultiBootStartMasterCalls;
extern u32 gHostTitleStubMultiBootCheckCompleteCalls;
extern u32 gHostTitleStubAddTextPrinterParameterized3Calls;
extern u32 gHostTitleStubLoadBgTilesCalls;
extern u32 gHostTitleStubFillBgTilemapBufferRectCalls;
extern u32 gHostTitleStubClearWindowTilemapCalls;
extern u32 gHostTitleStubRunTextPrintersCalls;
extern u32 gHostTitleStubIsTextPrinterActiveCalls;
extern u32 gHostTitleStubFreeAllSpritePalettesCalls;
extern u32 gHostTitleStubStartNewGameSceneCalls;
extern u32 gHostTitleStubTryStartQuestLogPlaybackCalls;
extern u32 gHostTitleStubCB2InitMysteryGiftCalls;
extern u32 gHostTitleStubIsWirelessAdapterConnectedCalls;
extern u32 gHostTitleStubIsMysteryGiftEnabledCalls;
extern u32 gHostTitleStubFlagGetCalls;
extern u32 gHostTitleStubGetNationalPokedexCountCalls;
extern u32 gHostTitleStubGetKantoPokedexCountCalls;
extern int gHostTitleStubLastMultiBootLength;
extern u8 gHostTitleStubLastHelpContext;
extern u8 gHostTitleStubLastFadeOutMapMusicSpeed;
extern u8 gHostTitleStubLastFadeOutBGMSpeed;
extern u16 gHostTitleStubLastPlayCrySpecies;
extern s8 gHostTitleStubLastPlayCryPan;
extern const u8 *gHostTitleStubLastPrintedText3;
extern bool8 gHostTitleStubWirelessAdapterConnected;
extern bool32 gHostTitleStubMysteryGiftEnabled;
extern bool8 gHostTitleStubNationalPokedexEnabled;
extern u16 gHostTitleStubNationalPokedexCount;
extern u16 gHostTitleStubKantoPokedexCount;
extern u8 gHostTitleStubFlagGetBadgeMask;
extern bool8 gHostTitleStubTextPrinterActive;
extern const u8 *gHostTitleStubLastPrintedText;
extern s8 gHostTitleStubMenuProcessInputResult;

void HostTitleScreenStubReset(void);
void HostTitleScreenStubSetMenuProcessInputResult(s8 result);

#endif
