#define _GNU_SOURCE
/*
 * pfr_play.c — Interactive player for pokefirered-native
 *
 * Opens an SDL2 window and runs the game's boot chain (copyright →
 * intro → title → main menu) with live keyboard input.
 *
 * Frame model: per-scanline rendering interleaved with HBlank DMA
 * and interrupt dispatch, matching real GBA hardware ordering.
 * The renderer processes one scanline at a time so that HBlank DMA
 * register changes (e.g. scanline scroll effects) are visible to
 * the next scanline.  HostDisplayPresent() handles display, input
 * polling, and 60 Hz frame pacing via VSYNC.
 *
 * Keyboard mapping (defined in host_display.c):
 *   Z=A  X=B  RShift=Select  Enter=Start
 *   Arrows=D-pad  S=R  A=L  Escape=Quit
 *   F1=hotload state  Shift+F1=overlay browse/load state file
 *   F2=hotsave state  Shift+F2=overlay browse/save state file
 *   Space=toggle turbo mode  Shift+Space=cycle turbo speeds
 *   F5=quicksave snapshot  F9=quickload snapshot + restart
 */

#include <stdio.h>
#include <stdlib.h>
#include <dirent.h>
#include <errno.h>
#include <sys/stat.h>
#include <string.h>
#include <dlfcn.h>
#include <unistd.h>
#include <signal.h>
#include <execinfo.h>
#include <limits.h>
#include <time.h>

#include "global.h"
#include "gba/gba.h"
#include "main.h"
#include "gpu_regs.h"
#include "intro.h"
#include "palette.h"
#include "task.h"
#include "sprite.h"
#include "bg.h"
#include "dma3.h"
#include "field_weather.h"
#include "play_time.h"
#include "malloc.h"
#include "load_save.h"
#include "pokemon.h"
#include "main_menu.h"
#include "oak_speech.h"
#include "save.h"
#include "sound.h"
#include "m4a.h"
#include "link_rfu.h"
#include "quest_log.h"
#include "help_system.h"
#include "new_menu_helpers.h"
#include "save_failed_screen.h"
#include "window.h"
#include "script.h"
#include "global.fieldmap.h"
#include "event_object_movement.h"
#include "battle_main.h"
#include "battle.h"
#include "host_sound_init.h"
#include "host_audio.h"
#include "host_flash.h"
#include "host_log.h"
#include "host_savestate.h"

/* Declared in main.c (non-static) but no header */
extern void EnableVCountIntrAtLine150(void);
extern void SetNotInSaveFailedScreen(void);
#include "title_screen.h"
#include "host_memory.h"
#include "host_renderer.h"
#include "host_display.h"
#include "host_crt0.h"
#include "host_intro_stubs.h"
#include "host_frame_step.h"
#include "overworld.h"
#include "host_new_game_stubs.h"
#include "host_oak_speech_stubs.h"
#include "host_title_screen_stubs.h"
#include "item.h"
#include "constants/items.h"

#ifndef PATH_MAX
#define PATH_MAX 4096
#endif

/* Patch functions generated by tools/script_assembler.py */
void HostPatchBattleScriptPointers(void);
void HostPatchEventScriptPointers(void);
void HostPatchFieldEffectScriptPointers(void);
void HostPatchBattleAIScriptPointers(void);
void HostPatchBattleAnimScriptPointers(void);

/* ── Save diagnostic ──────────────────────────────────────── */

void HostLogSaveStatus(u8 status)
{
    const char *name;

    switch (status)
    {
    case SAVE_STATUS_EMPTY:
        name = "EMPTY";
        break;
    case SAVE_STATUS_OK:
        name = "OK";
        break;
    case SAVE_STATUS_INVALID:
        name = "INVALID";
        break;
    case SAVE_STATUS_NO_FLASH:
        name = "NO_FLASH";
        break;
    case SAVE_STATUS_ERROR:
        name = "ERROR";
        break;
    default:
        name = "?";
        break;
    }
    HostLogPrintf("[pokefirered-native] LoadGameSave result: %s (%u)\n",
                  name, (unsigned)status);
}

/* ── Interrupt handlers ────────────────────────────────────── */

/* Oak speech text externs removed — StringExpandPlaceholders now from upstream */

static FILE *sTraceFile;
static char sActiveSavePath[PATH_MAX] = "pokefirered.sav";
static char sBootLoadSavePath[PATH_MAX];
static char sSnapshotDir[PATH_MAX] = "pfr_debug_saves";
static char sStateDir[PATH_MAX] = "pfr_debug_states";
static char sQuickLoadPath[PATH_MAX];
static char sControlFilePath[PATH_MAX];
static char **sProgramArgv;
static bool8 sBenchmarkEnabled;
static bool8 sBenchmarkCompleted;
static u32 sBenchmarkFrameLimit;
static u32 sEmulatedFrameCount;
static MainCallback sLastCallback1;
static MainCallback sLastCallback2;
static u32 sLastMainMenuInitCalls;
static u32 sLastStartNewGameSceneCalls;
static u32 sLastNamingCalls;
static u32 sLastControlsGuidePage1Loads;
static u32 sLastControlsGuidePage2Loads;
static u32 sLastControlsGuidePage3Loads;
static u32 sLastPikachuIntroPage1Loads;
static u32 sLastPikachuIntroPage2Loads;
static u32 sLastPikachuIntroPage3Loads;
static u32 sLastWelcomePrints;
static u32 sLastThisWorldPrints;
static u32 sLastIStudyPokemonPrints;
static u32 sLastAskPlayerGenderPrints;
static u32 sUniformFrameRunLength;
static u32 sLastUniformColor;
static bool8 sSnapshotRequested;
static char sSnapshotLabel[96];

#define MAX_SCRIPTED_INPUT_RANGES 256

struct ScriptedInputRange
{
    u32 startFrame;
    u32 endFrame;
    u16 pressedMask;
};

static struct ScriptedInputRange sScriptedInputRanges[MAX_SCRIPTED_INPUT_RANGES];
static u32 sScriptedInputRangeCount;
static bool8 sScriptedInputEnabled;
static bool8 sAutoPlayOakNewGameEnabled;
static bool8 sAutoPlayContinueEnabled;
static bool8 sAutoPlayOakLoggedGenderMenu;
static bool8 sAutoPlayOakLoggedNamingScreen;
static bool8 sAutoPlayOakLoggedRivalMenu;
static bool8 sAutoPlayOakLoggedOverworld;
static bool8 sAutoPlayContinueLoggedOverworld;
static u8 sAutoPlayOakGenderStep;
static u8 sAutoPlayOakNamingStep;
static u8 sAutoPlayOakRivalStep;
static u8 sAutoPlayOakWaitFrames;
static bool8 sTraceNamingFramesEnabled;
static bool8 sTraceOverworldStartupEnabled;
static bool8 sDebugGiveStarterEnabled;
static bool8 sDisableAudioEnabled;
static bool8 sFastModeEnabled;
static bool8 sRestartRequested;
static bool8 sShutdownRequested;
static bool8 sPresentRestoredFramePending;
static bool8 sTraceOverworldStartupActive;
static bool8 sTraceOverworldStartupCompleted;
static bool8 sTraceOverworldFirstVisibleLogged;
static u32 sTraceOverworldStartupFrame;

static void TraceLog(u32 frame, const char *message);
static const char *CallbackName(MainCallback callback);
static void RequestSnapshot(const char *label);
static void SanitizeSnapshotLabel(char *label);
static void TraceGpuState(u32 frame, const char *label);
static bool8 FlagEnabled(const char *value);
static bool8 ParseU32Option(const char *value, u32 *outValue);
static void SetPathOption(char *dest, size_t size, const char *value, const char *fallback);
static double TimespecDiffSeconds(const struct timespec *start, const struct timespec *end);
static void PrintBenchmarkSummary(double elapsedSeconds);
static bool8 EnsureDirectoryPath(const char *path);
static bool8 EnsureParentDirectoryForFile(const char *path);
static bool8 CopyFileToPath(const char *srcPath, const char *dstPath, bool8 overwrite);
static bool8 BuildChildPath(char *outPath, size_t outSize, const char *dirPath, const char *name);
static char *TrimAsciiWhitespace(char *text);
static bool8 BuildSnapshotPath(char *outPath, size_t outSize, u32 frame, const char *label);
static bool8 FindLatestSnapshotPath(char *outPath, size_t outSize);
static void LogAvailableSnapshots(u32 frame);
static bool8 SaveCurrentGameCopy(u32 frame, const char *action, const char *reason, const char *dstPath, bool8 overwrite);
static bool8 StageLoadFromSavePath(u32 frame, const char *action, const char *reason, const char *sourcePath);
static bool8 QuickSaveActiveGame(u32 frame, const char *reason);
static bool8 QuickLoadActiveGame(u32 frame, const char *reason);
static bool8 CaptureHotSavestate(u32 frame, const char *reason);
static bool8 RestoreHotSavestate(u32 frame, const char *reason);
static bool8 SaveSavestateToFileAtPath(u32 frame, const char *reason, const char *path);
static bool8 LoadSavestateFromFileAtPath(u32 frame, const char *reason, const char *path);
static bool8 RestartSelf(void);
static void ProcessControlCommand(u32 frame, const char *command);
static void ProcessControlFile(u32 frame);
static void HandleHostActions(u32 frame);
static u16 ComputeAutoPlayContinueInput(u32 frame);

static bool8 ShouldTraceDetailedFrame(u32 frame)
{
    const char *cb2Name = CallbackName(gMain.callback2);

    if (!sTraceNamingFramesEnabled)
        return FALSE;

    if (frame >= 4300)
        return TRUE;

    return strcmp(cb2Name, "CB2_LoadNamingScreen") == 0
        || strcmp(cb2Name, "CB2_NamingScreen") == 0
        || strcmp(cb2Name, "CB2_ReturnFromNamingScreen") == 0
        || strcmp(cb2Name, "CB2_NewGame") == 0
        || strcmp(cb2Name, "CB2_Overworld") == 0;
}

static u16 ParseInputToken(const char *token)
{
    if (strcmp(token, "A") == 0)
        return A_BUTTON;
    if (strcmp(token, "B") == 0)
        return B_BUTTON;
    if (strcmp(token, "SELECT") == 0)
        return SELECT_BUTTON;
    if (strcmp(token, "START") == 0)
        return START_BUTTON;
    if (strcmp(token, "RIGHT") == 0)
        return DPAD_RIGHT;
    if (strcmp(token, "LEFT") == 0)
        return DPAD_LEFT;
    if (strcmp(token, "UP") == 0)
        return DPAD_UP;
    if (strcmp(token, "DOWN") == 0)
        return DPAD_DOWN;
    if (strcmp(token, "R") == 0)
        return R_BUTTON;
    if (strcmp(token, "L") == 0)
        return L_BUTTON;
    if (strcmp(token, "NONE") == 0)
        return 0;
    return 0xFFFF;
}

static bool8 ParseInputMask(const char *maskText, u16 *outMask)
{
    char buffer[128];
    char *token;
    char *savePtr = NULL;
    u16 mask = 0;

    if (strncmp(maskText, "0x", 2) == 0 || strncmp(maskText, "0X", 2) == 0)
    {
        char *endPtr = NULL;
        unsigned long value = strtoul(maskText, &endPtr, 16);

        if (endPtr == NULL || *endPtr != '\0')
            return FALSE;
        *outMask = (u16)value;
        return TRUE;
    }

    snprintf(buffer, sizeof(buffer), "%.127s", maskText);
    token = strtok_r(buffer, "+|,", &savePtr);
    while (token != NULL)
    {
        u16 value = ParseInputToken(token);

        if (value == 0xFFFF)
            return FALSE;
        mask |= value;
        token = strtok_r(NULL, "+|,", &savePtr);
    }

    *outMask = mask;
    return TRUE;
}

static bool8 LoadScriptedInputFile(const char *path)
{
    FILE *file = fopen(path, "r");
    char line[256];
    u32 lineNumber = 0;

    if (file == NULL)
    {
        fprintf(stderr, "pfr_play: could not open input script %s\n", path);
        return FALSE;
    }

    sScriptedInputRangeCount = 0;
    while (fgets(line, sizeof(line), file) != NULL)
    {
        char *hash;
        char *startText;
        char *endText;
        char *maskText;
        char *savePtr = NULL;
        unsigned long startFrame;
        unsigned long endFrame;
        u16 mask;

        lineNumber++;
        hash = strchr(line, '#');
        if (hash != NULL)
            *hash = '\0';

        startText = strtok_r(line, " \t\r\n", &savePtr);
        if (startText == NULL)
            continue;
        endText = strtok_r(NULL, " \t\r\n", &savePtr);
        maskText = strtok_r(NULL, " \t\r\n", &savePtr);

        if (endText == NULL || maskText == NULL)
        {
            fprintf(stderr, "pfr_play: malformed input script line %u\n", lineNumber);
            fclose(file);
            return FALSE;
        }

        startFrame = strtoul(startText, NULL, 10);
        endFrame = strtoul(endText, NULL, 10);
        if (endFrame < startFrame)
        {
            fprintf(stderr, "pfr_play: invalid frame range on line %u\n", lineNumber);
            fclose(file);
            return FALSE;
        }

        if (!ParseInputMask(maskText, &mask))
        {
            fprintf(stderr, "pfr_play: invalid input mask on line %u: %s\n", lineNumber, maskText);
            fclose(file);
            return FALSE;
        }

        if (sScriptedInputRangeCount >= MAX_SCRIPTED_INPUT_RANGES)
        {
            fprintf(stderr, "pfr_play: too many scripted input ranges\n");
            fclose(file);
            return FALSE;
        }

        sScriptedInputRanges[sScriptedInputRangeCount].startFrame = (u32)startFrame;
        sScriptedInputRanges[sScriptedInputRangeCount].endFrame = (u32)endFrame;
        sScriptedInputRanges[sScriptedInputRangeCount].pressedMask = mask;
        sScriptedInputRangeCount++;
    }

    fclose(file);
    sScriptedInputEnabled = TRUE;
    return TRUE;
}

static bool8 WindowMatches(u8 windowId, u8 bg, u8 tilemapLeft, u8 tilemapTop, u8 width, u8 height)
{
    return windowId < WINDOWS_MAX
        && gWindows[windowId].tileData != NULL
        && gWindows[windowId].window.bg == bg
        && gWindows[windowId].window.tilemapLeft == tilemapLeft
        && gWindows[windowId].window.tilemapTop == tilemapTop
        && gWindows[windowId].window.width == width
        && gWindows[windowId].window.height == height;
}

static int FindWindowIdMatching(u8 bg, u8 tilemapLeft, u8 tilemapTop, u8 width, u8 height)
{
    int i;

    for (i = 0; i < WINDOWS_MAX; i++)
    {
        if (WindowMatches(i, bg, tilemapLeft, tilemapTop, width, height))
            return i;
    }

    return -1;
}

static bool8 FlagEnabled(const char *value)
{
    return value != NULL && value[0] != '\0' && strcmp(value, "0") != 0;
}

static bool8 ParseU32Option(const char *value, u32 *outValue)
{
    char *end = NULL;
    unsigned long parsed;

    if (value == NULL || value[0] == '\0')
        return FALSE;

    parsed = strtoul(value, &end, 10);
    if (end == NULL || *end != '\0' || parsed == 0 || parsed > 1000000ul)
        return FALSE;

    *outValue = (u32)parsed;
    return TRUE;
}

static void SetPathOption(char *dest, size_t size, const char *value, const char *fallback)
{
    const char *source = value;

    if (source == NULL || source[0] == '\0')
        source = fallback;

    if (source == NULL)
    {
        dest[0] = '\0';
        return;
    }

    snprintf(dest, size, "%s", source);
}

static double TimespecDiffSeconds(const struct timespec *start, const struct timespec *end)
{
    time_t seconds = end->tv_sec - start->tv_sec;
    long nanoseconds = end->tv_nsec - start->tv_nsec;

    if (nanoseconds < 0)
    {
        seconds--;
        nanoseconds += 1000000000L;
    }

    return (double)seconds + (double)nanoseconds / 1000000000.0;
}

static void PrintBenchmarkSummary(double elapsedSeconds)
{
    double emulatedFps = 0.0;
    double speedupVsRealtime = 0.0;

    if (elapsedSeconds > 0.0)
    {
        emulatedFps = (double)sEmulatedFrameCount / elapsedSeconds;
        speedupVsRealtime = emulatedFps / 60.0;
    }

    printf("benchmark_result mode=pfr_play emulated_frames=%u presents=%u elapsed_seconds=%.6f emulated_fps=%.2f speedup_vs_realtime=%.2f\n",
           sEmulatedFrameCount,
           HostDisplayGetFrameCount(),
           elapsedSeconds,
           emulatedFps,
           speedupVsRealtime);
    fflush(stdout);
}

static bool8 EnsureDirectoryPath(const char *path)
{
    char scratch[PATH_MAX];
    size_t len;
    size_t i;

    if (path == NULL || path[0] == '\0')
        return FALSE;

    len = strlen(path);
    if (len >= sizeof(scratch))
        return FALSE;

    snprintf(scratch, sizeof(scratch), "%s", path);
    for (i = 1; i < len; i++)
    {
        if (scratch[i] != '/')
            continue;

        scratch[i] = '\0';
        if (scratch[0] != '\0' && mkdir(scratch, 0775) != 0 && errno != EEXIST)
            return FALSE;
        scratch[i] = '/';
    }

    if (mkdir(scratch, 0775) != 0 && errno != EEXIST)
        return FALSE;

    return TRUE;
}

static bool8 EnsureParentDirectoryForFile(const char *path)
{
    char scratch[PATH_MAX];
    char *slash;

    if (path == NULL || path[0] == '\0')
        return FALSE;

    snprintf(scratch, sizeof(scratch), "%s", path);
    slash = strrchr(scratch, '/');
    if (slash == NULL)
        return TRUE;

    if (slash == scratch)
        slash[1] = '\0';
    else
        *slash = '\0';

    return EnsureDirectoryPath(scratch);
}

static bool8 CopyFileToPath(const char *srcPath, const char *dstPath, bool8 overwrite)
{
    FILE *src = NULL;
    FILE *dst = NULL;
    char tmpPath[PATH_MAX];
    unsigned char buffer[8192];
    size_t bytesRead;
    bool8 ok = FALSE;

    if (srcPath == NULL || dstPath == NULL || srcPath[0] == '\0' || dstPath[0] == '\0')
        return FALSE;

    if (strcmp(srcPath, dstPath) == 0)
        return TRUE;

    if (!overwrite && access(dstPath, F_OK) == 0)
        return FALSE;

    if (!EnsureParentDirectoryForFile(dstPath))
        return FALSE;

    src = fopen(srcPath, "rb");
    if (src == NULL)
        return FALSE;

    snprintf(tmpPath, sizeof(tmpPath), "%s.tmp", dstPath);
    dst = fopen(tmpPath, "wb");
    if (dst == NULL)
        goto cleanup;

    while ((bytesRead = fread(buffer, 1, sizeof(buffer), src)) != 0)
    {
        if (fwrite(buffer, 1, bytesRead, dst) != bytesRead)
            goto cleanup;
    }

    if (ferror(src))
        goto cleanup;

    if (fclose(dst) != 0)
    {
        dst = NULL;
        goto cleanup;
    }
    dst = NULL;

    if (overwrite)
    {
        if (rename(tmpPath, dstPath) != 0)
            goto cleanup;
    }
    else
    {
        if (link(tmpPath, dstPath) != 0)
            goto cleanup;
        if (unlink(tmpPath) != 0)
        {
            unlink(dstPath);
            goto cleanup;
        }
    }

    ok = TRUE;

cleanup:
    if (dst != NULL)
        fclose(dst);
    if (!ok)
        unlink(tmpPath);
    if (src != NULL)
        fclose(src);
    return ok;
}

static bool8 BuildChildPath(char *outPath, size_t outSize, const char *dirPath, const char *name)
{
    size_t dirLen;
    size_t nameLen;

    if (outPath == NULL || outSize == 0 || dirPath == NULL || name == NULL)
        return FALSE;

    dirLen = strlen(dirPath);
    nameLen = strlen(name);
    if (dirLen == 0 || dirLen + 1 + nameLen + 1 > outSize)
        return FALSE;

    memcpy(outPath, dirPath, dirLen);
    outPath[dirLen] = '/';
    memcpy(outPath + dirLen + 1, name, nameLen + 1);
    return TRUE;
}

static char *TrimAsciiWhitespace(char *text)
{
    char *end;

    while (*text == ' ' || *text == '\t' || *text == '\r' || *text == '\n')
        text++;

    end = text + strlen(text);
    while (end > text
        && (end[-1] == ' ' || end[-1] == '\t' || end[-1] == '\r' || end[-1] == '\n'))
    {
        *--end = '\0';
    }

    return text;
}

static bool8 BuildSnapshotPath(char *outPath, size_t outSize, u32 frame, const char *label)
{
    time_t now;
    struct tm tmNow;
    char safeLabel[96];

    if (!EnsureDirectoryPath(sSnapshotDir))
        return FALSE;

    now = time(NULL);
    if (localtime_r(&now, &tmNow) == NULL)
        return FALSE;

    if (label != NULL && label[0] != '\0')
    {
        snprintf(safeLabel, sizeof(safeLabel), "%.95s", label);
        SanitizeSnapshotLabel(safeLabel);
        snprintf(outPath, outSize,
                 "%s/%04d%02d%02d_%02d%02d%02d_frame%06u_%s.sav",
                 sSnapshotDir,
                 tmNow.tm_year + 1900,
                 tmNow.tm_mon + 1,
                 tmNow.tm_mday,
                 tmNow.tm_hour,
                 tmNow.tm_min,
                 tmNow.tm_sec,
                 frame,
                 safeLabel);
    }
    else
    {
        snprintf(outPath, outSize,
                 "%s/%04d%02d%02d_%02d%02d%02d_frame%06u.sav",
                 sSnapshotDir,
                 tmNow.tm_year + 1900,
                 tmNow.tm_mon + 1,
                 tmNow.tm_mday,
                 tmNow.tm_hour,
                 tmNow.tm_min,
                 tmNow.tm_sec,
                 frame);
    }
    return TRUE;
}

static bool8 FindLatestSnapshotPath(char *outPath, size_t outSize)
{
    DIR *dir;
    struct dirent *entry;
    char path[PATH_MAX];
    struct stat st;
    time_t bestTime = 0;
    bool8 found = FALSE;

    dir = opendir(sSnapshotDir);
    if (dir == NULL)
        return FALSE;

    while ((entry = readdir(dir)) != NULL)
    {
        size_t nameLen = strlen(entry->d_name);

        if (nameLen < 4 || strcmp(entry->d_name + nameLen - 4, ".sav") != 0)
            continue;
        if (!BuildChildPath(path, sizeof(path), sSnapshotDir, entry->d_name))
            continue;

        if (stat(path, &st) != 0 || !S_ISREG(st.st_mode))
            continue;

        if (!found || st.st_mtime > bestTime)
        {
            bestTime = st.st_mtime;
            snprintf(outPath, outSize, "%s", path);
            found = TRUE;
        }
    }

    closedir(dir);
    return found;
}

static void LogAvailableSnapshots(u32 frame)
{
    DIR *dir;
    struct dirent *entry;
    char path[PATH_MAX];
    char buffer[PATH_MAX + 64];
    u32 count = 0;

    dir = opendir(sSnapshotDir);
    if (dir == NULL)
    {
        snprintf(buffer, sizeof(buffer), "snapshot list: directory unavailable (%s)", sSnapshotDir);
        TraceLog(frame, buffer);
        return;
    }

    while ((entry = readdir(dir)) != NULL)
    {
        size_t nameLen = strlen(entry->d_name);

        if (nameLen < 4 || strcmp(entry->d_name + nameLen - 4, ".sav") != 0)
            continue;
        if (!BuildChildPath(path, sizeof(path), sSnapshotDir, entry->d_name))
            continue;

        snprintf(buffer, sizeof(buffer), "snapshot[%u]: %s", count, path);
        TraceLog(frame, buffer);
        count++;
    }

    if (count == 0)
        TraceLog(frame, "snapshot list: no .sav files found");

    closedir(dir);
}

static void ResetAutoPlayOakState(void)
{
    sAutoPlayOakLoggedGenderMenu = FALSE;
    sAutoPlayOakLoggedNamingScreen = FALSE;
    sAutoPlayOakLoggedRivalMenu = FALSE;
    sAutoPlayOakLoggedOverworld = FALSE;
    sAutoPlayContinueLoggedOverworld = FALSE;
    sAutoPlayOakGenderStep = 0;
    sAutoPlayOakNamingStep = 0;
    sAutoPlayOakRivalStep = 0;
    sAutoPlayOakWaitFrames = 0;
}

static bool8 SaveCurrentGameCopy(u32 frame, const char *action, const char *reason, const char *dstPath, bool8 overwrite)
{
    char buffer[PATH_MAX * 2 + 128];

    if (sActiveSavePath[0] == '\0' || dstPath == NULL || dstPath[0] == '\0')
        return FALSE;

    if (gMain.callback1 == CB1_Overworld && strcmp(CallbackName(gMain.callback2), "CB2_Overworld") == 0)
    {
        u8 status = TrySavingData(SAVE_NORMAL);
        if (status != SAVE_STATUS_OK)
        {
            snprintf(buffer, sizeof(buffer),
                     "%s (%s) failed: TrySavingData status=%u",
                     action,
                     reason,
                     status);
            TraceLog(frame, buffer);
            return FALSE;
        }
    }
    else
    {
        snprintf(buffer, sizeof(buffer),
                 "%s (%s): not in overworld, exporting last persisted save only",
                 action,
                 reason);
        TraceLog(frame, buffer);
    }

    if (!CopyFileToPath(sActiveSavePath, dstPath, overwrite))
    {
        snprintf(buffer, sizeof(buffer),
                 "%s (%s) failed copying %s -> %s",
                 action,
                 reason,
                 sActiveSavePath,
                 dstPath);
        TraceLog(frame, buffer);
        return FALSE;
    }

    snprintf(buffer, sizeof(buffer),
             "%s (%s): %s -> %s",
             action,
             reason,
             sActiveSavePath,
             dstPath);
    TraceLog(frame, buffer);
    return TRUE;
}

static bool8 StageLoadFromSavePath(u32 frame, const char *action, const char *reason, const char *sourcePath)
{
    char buffer[PATH_MAX * 2 + 128];

    if (sActiveSavePath[0] == '\0' || sourcePath == NULL || sourcePath[0] == '\0')
        return FALSE;

    if (!CopyFileToPath(sourcePath, sActiveSavePath, TRUE))
    {
        snprintf(buffer, sizeof(buffer),
                 "%s (%s) failed copying %s -> %s",
                 action,
                 reason,
                 sourcePath,
                 sActiveSavePath);
        TraceLog(frame, buffer);
        return FALSE;
    }

    setenv("PFR_AUTOPLAY_CONTINUE", "1", 1);
    sRestartRequested = TRUE;
    snprintf(buffer, sizeof(buffer),
             "%s (%s): staged %s -> %s, restarting",
             action,
             reason,
             sourcePath,
             sActiveSavePath);
    TraceLog(frame, buffer);
    return TRUE;
}

static u16 ComputeAutoPlayContinueInput(u32 frame)
{
    const char *cb2Name;

    if (!sAutoPlayContinueEnabled)
        return 0;

    cb2Name = CallbackName(gMain.callback2);
    if (!sAutoPlayContinueLoggedOverworld
     && gMain.callback1 == CB1_Overworld
     && strcmp(cb2Name, "CB2_Overworld") == 0)
    {
        sAutoPlayContinueLoggedOverworld = TRUE;
        TraceLog(frame, "autoplay: continued save reached overworld");
        RequestSnapshot("autoplay_continue_overworld");
        return 0;
    }

    if (strcmp(cb2Name, "CB2_TitleScreenRun") == 0)
        return (frame % 32 == 0) ? START_BUTTON : 0;

    if (strcmp(cb2Name, "CB2_InitMainMenu") == 0 || strcmp(cb2Name, "CB2_MainMenu") == 0)
        return (frame % 12 == 0) ? A_BUTTON : 0;

    return 0;
}

static bool8 QuickSaveActiveGame(u32 frame, const char *reason)
{
    char snapshotPath[PATH_MAX];

    if (!BuildSnapshotPath(snapshotPath, sizeof(snapshotPath), frame, reason))
    {
        TraceLog(frame, "quicksave: could not build snapshot path");
        return FALSE;
    }

    return SaveCurrentGameCopy(frame, "quicksave", reason, snapshotPath, FALSE);
}

static bool8 QuickLoadActiveGame(u32 frame, const char *reason)
{
    char sourcePath[PATH_MAX];

    if (sQuickLoadPath[0] != '\0')
        snprintf(sourcePath, sizeof(sourcePath), "%s", sQuickLoadPath);
    else if (!FindLatestSnapshotPath(sourcePath, sizeof(sourcePath)))
    {
        TraceLog(frame, "quickload: no snapshot found");
        return FALSE;
    }

    return StageLoadFromSavePath(frame, "quickload", reason, sourcePath);
}

static bool8 CaptureHotSavestate(u32 frame, const char *reason)
{
    char buffer[384];

    HostAudioLock();
    if (!HostSavestateCaptureHot())
    {
        HostAudioUnlock();
        snprintf(buffer, sizeof(buffer), "state save (%s) failed: %s", reason, HostSavestateGetLastError());
        TraceLog(frame, buffer);
        return FALSE;
    }
    HostAudioUnlock();

    snprintf(buffer, sizeof(buffer), "state save (%s): captured hot snapshot", reason);
    TraceLog(frame, buffer);
    return TRUE;
}

static bool8 RestoreHotSavestate(u32 frame, const char *reason)
{
    char buffer[384];

    HostAudioLock();
    if (!HostSavestateRestoreHot())
    {
        HostAudioUnlock();
        snprintf(buffer, sizeof(buffer), "state load (%s) failed: %s", reason, HostSavestateGetLastError());
        TraceLog(frame, buffer);
        return FALSE;
    }
    HostAudioResetBufferedSamples();
    HostAudioUnlock();

    sPresentRestoredFramePending = TRUE;
    snprintf(buffer, sizeof(buffer), "state load (%s): restored hot snapshot", reason);
    TraceLog(frame, buffer);
    return TRUE;
}

static bool8 SaveSavestateToFileAtPath(u32 frame, const char *reason, const char *path)
{
    char buffer[PATH_MAX + 384];

    if (!EnsureParentDirectoryForFile(path))
    {
        snprintf(buffer, sizeof(buffer), "state save-as (%s) failed: could not create parent directory for %s", reason, path);
        TraceLog(frame, buffer);
        return FALSE;
    }

    HostAudioLock();
    if (!HostSavestateSaveToFile(path))
    {
        HostAudioUnlock();
        snprintf(buffer, sizeof(buffer), "state save-as (%s) failed: %s", reason, HostSavestateGetLastError());
        TraceLog(frame, buffer);
        return FALSE;
    }
    HostAudioUnlock();

    snprintf(buffer, sizeof(buffer), "state save-as (%s): %s", reason, path);
    TraceLog(frame, buffer);
    return TRUE;
}

static bool8 LoadSavestateFromFileAtPath(u32 frame, const char *reason, const char *path)
{
    char buffer[PATH_MAX + 384];

    HostAudioLock();
    if (!HostSavestateLoadFromFile(path))
    {
        HostAudioUnlock();
        snprintf(buffer, sizeof(buffer), "state load-as (%s) failed: %s", reason, HostSavestateGetLastError());
        TraceLog(frame, buffer);
        return FALSE;
    }
    HostAudioResetBufferedSamples();
    HostAudioUnlock();

    sPresentRestoredFramePending = TRUE;
    snprintf(buffer, sizeof(buffer), "state load-as (%s): %s", reason, path);
    TraceLog(frame, buffer);
    return TRUE;
}

static bool8 RestartSelf(void)
{
    if (sProgramArgv == NULL || sProgramArgv[0] == NULL)
        return FALSE;

    fflush(NULL);
    execvp(sProgramArgv[0], sProgramArgv);
    return FALSE;
}

static void ProcessControlCommand(u32 frame, const char *command)
{
    char buffer[PATH_MAX + 128];
    char line[PATH_MAX + 128];
    char *arg;

    snprintf(line, sizeof(line), "%s", command);
    arg = line;
    while (*arg != '\0' && *arg != ' ' && *arg != '\t')
        arg++;

    if (*arg != '\0')
        *arg++ = '\0';
    arg = TrimAsciiWhitespace(arg);

    if (strcmp(line, "quicksave") == 0)
    {
        QuickSaveActiveGame(frame, (arg[0] != '\0') ? arg : "control");
    }
    else if (strcmp(line, "hotsave") == 0)
    {
        CaptureHotSavestate(frame, "control");
    }
    else if (strcmp(line, "hotload") == 0)
    {
        RestoreHotSavestate(frame, "control");
    }
    else if (strcmp(line, "statesave") == 0)
    {
        if (arg[0] == '\0')
        {
            TraceLog(frame, "control: statesave requires a destination path");
            return;
        }
        SaveSavestateToFileAtPath(frame, "control", arg);
    }
    else if (strcmp(line, "stateload") == 0)
    {
        if (arg[0] == '\0')
        {
            TraceLog(frame, "control: stateload requires a source path");
            return;
        }
        LoadSavestateFromFileAtPath(frame, "control", arg);
    }
    else if (strcmp(line, "saveas") == 0)
    {
        if (arg[0] == '\0')
        {
            TraceLog(frame, "control: saveas requires a destination path");
            return;
        }
        SaveCurrentGameCopy(frame, "saveas", "control", arg, FALSE);
    }
    else if (strcmp(line, "quickload") == 0)
    {
        if (arg[0] != '\0')
            StageLoadFromSavePath(frame, "quickload", "control", arg);
        else
            QuickLoadActiveGame(frame, "control");
    }
    else if (strcmp(line, "load") == 0)
    {
        if (arg[0] == '\0')
        {
            TraceLog(frame, "control: load requires a source path");
            return;
        }
        StageLoadFromSavePath(frame, "load", "control", arg);
    }
    else if (strcmp(line, "list") == 0)
    {
        LogAvailableSnapshots(frame);
    }
    else if (strcmp(line, "quit") == 0)
    {
        sShutdownRequested = TRUE;
        TraceLog(frame, "control: quit requested");
    }
    else
    {
        snprintf(buffer, sizeof(buffer), "control: unknown command '%.200s'", line);
        TraceLog(frame, buffer);
    }
}

static void ProcessControlFile(u32 frame)
{
    struct stat st;
    FILE *file;
    char line[PATH_MAX + 128];

    if (sControlFilePath[0] == '\0')
        return;

    if (stat(sControlFilePath, &st) != 0)
        return;

    if (!S_ISREG(st.st_mode))
    {
        TraceLog(frame, "control: path exists but is not a regular file");
        return;
    }

    file = fopen(sControlFilePath, "r");
    if (file == NULL)
    {
        TraceLog(frame, "control: failed to open command file");
        return;
    }

    while (fgets(line, sizeof(line), file) != NULL)
    {
        char *hash = strchr(line, '#');
        char *command;

        if (hash != NULL)
            *hash = '\0';

        command = TrimAsciiWhitespace(line);
        if (command[0] == '\0')
            continue;

        ProcessControlCommand(frame, command);
        if (sRestartRequested || sShutdownRequested)
            break;
    }

    fclose(file);
    if (unlink(sControlFilePath) != 0)
        TraceLog(frame, "control: failed to consume command file");
}

static const char *const sPocketNames[] = {
    "Items", "Key Items", "Poke Balls", "TM Case", "Berry Pouch"
};

static void RepairBag(u32 frame)
{
    static const u8 sPocketCapacities[] = {
        BAG_ITEMS_COUNT, BAG_KEYITEMS_COUNT, BAG_POKEBALLS_COUNT,
        BAG_TMHM_COUNT, BAG_BERRIES_COUNT
    };
    char buf[256];
    u32 p, j;
    u32 totalRepaired = 0;
    u32 encKey;

    if (gSaveBlock1Ptr == NULL || gSaveBlock2Ptr == NULL)
    {
        TraceLog(frame, "bag_repair: save blocks not initialized");
        return;
    }

    encKey = gSaveBlock2Ptr->encryptionKey;
    snprintf(buf, sizeof(buf), "bag_repair: encryptionKey=0x%08X", encKey);
    TraceLog(frame, buf);

    /* Re-establish bag pocket pointers in case they're stale */
    SetBagPocketsPointers();

    for (p = 0; p < NUM_BAG_POCKETS; p++)
    {
        struct BagPocket *pocket = &gBagPockets[p];
        u8 expectedCap = sPocketCapacities[p];
        u32 pocketRepaired = 0;

        if (pocket->capacity != expectedCap)
        {
            snprintf(buf, sizeof(buf), "bag_repair: pocket %s capacity=%u (expected %u) -- fixing",
                     sPocketNames[p], pocket->capacity, expectedCap);
            TraceLog(frame, buf);
            pocket->capacity = expectedCap;
            pocketRepaired++;
        }

        if (pocket->itemSlots == NULL)
        {
            snprintf(buf, sizeof(buf), "bag_repair: pocket %s has NULL itemSlots", sPocketNames[p]);
            TraceLog(frame, buf);
            continue;
        }

        for (j = 0; j < pocket->capacity; j++)
        {
            struct ItemSlot *slot = &pocket->itemSlots[j];
            u16 rawQty = slot->quantity;
            u16 decQty = rawQty ^ (u16)encKey;

            if (slot->itemId == ITEM_NONE)
            {
                if (rawQty != 0)
                {
                    snprintf(buf, sizeof(buf), "bag_repair: %s[%u] itemId=NONE but rawQty=0x%04X -- clearing",
                             sPocketNames[p], j, rawQty);
                    TraceLog(frame, buf);
                    slot->quantity = 0;
                    pocketRepaired++;
                }
                continue;
            }

            if (slot->itemId >= ITEMS_COUNT)
            {
                snprintf(buf, sizeof(buf), "bag_repair: %s[%u] invalid itemId=%u (max=%u) -- clearing slot",
                         sPocketNames[p], j, slot->itemId, ITEMS_COUNT - 1);
                TraceLog(frame, buf);
                slot->itemId = ITEM_NONE;
                slot->quantity = 0;
                pocketRepaired++;
                continue;
            }

            if (decQty > 999)
            {
                snprintf(buf, sizeof(buf), "bag_repair: %s[%u] itemId=%u decQty=%u (raw=0x%04X) -- clamping to 1",
                         sPocketNames[p], j, slot->itemId, decQty, rawQty);
                TraceLog(frame, buf);
                slot->quantity = 1 ^ (u16)encKey;
                pocketRepaired++;
            }

            {
                u8 correctPocket = ItemId_GetPocket(slot->itemId);
                if (correctPocket != 0 && (correctPocket - 1) != p)
                {
                    snprintf(buf, sizeof(buf), "bag_repair: %s[%u] itemId=%u belongs in pocket %u -- clearing",
                             sPocketNames[p], j, slot->itemId, correctPocket - 1);
                    TraceLog(frame, buf);
                    slot->itemId = ITEM_NONE;
                    slot->quantity = 0;
                    pocketRepaired++;
                }
            }
        }

        if (pocketRepaired > 0)
        {
            BagPocketCompaction(pocket->itemSlots, pocket->capacity);
            snprintf(buf, sizeof(buf), "bag_repair: %s -- repaired %u slots, compacted",
                     sPocketNames[p], pocketRepaired);
            TraceLog(frame, buf);
        }
        else
        {
            u32 usedSlots = 0;
            for (j = 0; j < pocket->capacity; j++)
            {
                if (pocket->itemSlots[j].itemId != ITEM_NONE)
                    usedSlots++;
            }
            snprintf(buf, sizeof(buf), "bag_repair: %s -- %u/%u slots used, OK",
                     sPocketNames[p], usedSlots, pocket->capacity);
            TraceLog(frame, buf);
        }

        totalRepaired += pocketRepaired;
    }

    snprintf(buf, sizeof(buf), "bag_repair: done -- %u total repairs", totalRepaired);
    TraceLog(frame, buf);
}

static void HandleHostActions(u32 frame)
{
    u32 actions = HostDisplayConsumeActions();
    char path[PATH_MAX];

    if (actions & HOST_DISPLAY_ACTION_QUICKSAVE)
        QuickSaveActiveGame(frame, "hotkey");

    if (actions & HOST_DISPLAY_ACTION_QUICKLOAD)
        QuickLoadActiveGame(frame, "hotkey");

    if (actions & HOST_DISPLAY_ACTION_STATE_SAVE)
        CaptureHotSavestate(frame, "hotkey");

    if (actions & HOST_DISPLAY_ACTION_STATE_LOAD)
        RestoreHotSavestate(frame, "hotkey");

    if ((actions & HOST_DISPLAY_ACTION_STATE_SAVE_AS)
     && HostDisplayConsumeSelectedStatePath(path, sizeof(path)))
    {
        SaveSavestateToFileAtPath(frame, "hotkey", path);
    }

    if ((actions & HOST_DISPLAY_ACTION_STATE_LOAD_AS)
     && HostDisplayConsumeSelectedStatePath(path, sizeof(path)))
    {
        LoadSavestateFromFileAtPath(frame, "hotkey", path);
    }

    if (actions & HOST_DISPLAY_ACTION_REPAIR_BAG)
        RepairBag(frame);

    ProcessControlFile(frame);
}

static u16 ComputeAutoPlayOakInput(u32 frame)
{
    int genderWindowId;
    int yesNoWindowId;
    int rivalWindowId;
    const char *cb2Name;

    if (!sAutoPlayOakNewGameEnabled)
        return 0;

    cb2Name = CallbackName(gMain.callback2);
    genderWindowId = FindWindowIdMatching(0, 18, 9, 9, 4);
    yesNoWindowId = FindWindowIdMatching(0, 2, 2, 6, 4);
    rivalWindowId = FindWindowIdMatching(0, 2, 2, 12, 10);

    if (!sAutoPlayOakLoggedOverworld
     && gMain.callback1 == CB1_Overworld
     && strcmp(cb2Name, "CB2_Overworld") == 0)
    {
        sAutoPlayOakLoggedOverworld = TRUE;
        TraceLog(frame, "autoplay: overworld reached");
        RequestSnapshot("autoplay_overworld_reached");
        if (sDebugGiveStarterEnabled)
        {
            extern bool8 ScriptGiveMon(u16 species, u8 level, u16 item, u32 unk1, u32 unk2, u8 unk3);
            extern u8 FlagSet(u16 id);
            extern bool8 VarSet(u16 id, u16 value);
            ScriptGiveMon(1, 5, 0, 0, 0, 0);  /* SPECIES_BULBASAUR lv5 */
            FlagSet(0x828);  /* FLAG_SYS_POKEMON_GET */
            VarSet(0x4050, 1);  /* VAR_MAP_SCENE_PALLET_TOWN_OAK = 1 (skip Oak event) */
            VarSet(0x4053, 3);  /* VAR_MAP_SCENE_PALLET_TOWN_PROFESSOR_OAKS_LAB = 3 */
            TraceLog(frame, "debug: gave Bulbasaur lv5, set flags to skip Oak sequence");
        }
        return 0;
    }

    if (sAutoPlayOakWaitFrames != 0)
    {
        sAutoPlayOakWaitFrames--;
        return 0;
    }

    if (genderWindowId >= 0)
    {
        if (!sAutoPlayOakLoggedGenderMenu)
        {
            sAutoPlayOakLoggedGenderMenu = TRUE;
            TraceLog(frame, "autoplay: gender menu detected");
        }

        if (sAutoPlayOakGenderStep == 0)
        {
            sAutoPlayOakGenderStep = 1;
            sAutoPlayOakWaitFrames = 1;
            return DPAD_DOWN;
        }
        if (sAutoPlayOakGenderStep == 1)
        {
            sAutoPlayOakGenderStep = 2;
            sAutoPlayOakWaitFrames = 1;
            return A_BUTTON;
        }
        return 0;
    }

    if (strcmp(cb2Name, "CB2_LoadNamingScreen") == 0
     || strcmp(cb2Name, "CB2_ReturnFromNamingScreen") == 0)
    {
        return 0;
    }

    if (strcmp(cb2Name, "CB2_NamingScreen") == 0)
    {
        if (!sAutoPlayOakLoggedNamingScreen)
        {
            sAutoPlayOakLoggedNamingScreen = TRUE;
            TraceLog(frame, "autoplay: player naming screen detected");
        }

        if (sAutoPlayOakNamingStep == 0)
        {
            if (gPaletteFade.active)
                return 0;

            sAutoPlayOakNamingStep = 1;
            sAutoPlayOakWaitFrames = 32;
            return 0;
        }
        if (sAutoPlayOakNamingStep == 1)
        {
            sAutoPlayOakNamingStep = 2;
            sAutoPlayOakWaitFrames = 8;
            return START_BUTTON;
        }
        if (sAutoPlayOakNamingStep == 2)
        {
            sAutoPlayOakNamingStep = 3;
            sAutoPlayOakWaitFrames = 1;
            return A_BUTTON;
        }
        return 0;
    }

    if (rivalWindowId >= 0)
    {
        if (!sAutoPlayOakLoggedRivalMenu)
        {
            sAutoPlayOakLoggedRivalMenu = TRUE;
            TraceLog(frame, "autoplay: rival naming menu detected");
        }

        if (sAutoPlayOakRivalStep == 0 || sAutoPlayOakRivalStep == 1)
        {
            sAutoPlayOakRivalStep++;
            sAutoPlayOakWaitFrames = 1;
            return DPAD_DOWN;
        }
        if (sAutoPlayOakRivalStep == 2)
        {
            sAutoPlayOakRivalStep = 3;
            sAutoPlayOakWaitFrames = 1;
            return A_BUTTON;
        }
        return 0;
    }

    if (yesNoWindowId >= 0)
    {
        sAutoPlayOakWaitFrames = 1;
        return A_BUTTON;
    }

    if (strcmp(cb2Name, "CB2_TitleScreenRun") == 0)
        return (frame % 32 == 0) ? START_BUTTON : 0;

    if (strcmp(cb2Name, "CB2_InitMainMenu") == 0 || strcmp(cb2Name, "CB2_MainMenu") == 0)
        return (frame % 12 == 0) ? A_BUTTON : 0;

    if (strcmp(cb2Name, "CB2_NewGameScene") == 0)
        return (frame % 16 == 0) ? A_BUTTON : 0;

    return 0;
}

static void ApplyScriptedInput(u32 frame)
{
    u16 pressedMask = 0;
    u32 i;

    if (sScriptedInputEnabled)
    {
        for (i = 0; i < sScriptedInputRangeCount; i++)
        {
            if (frame >= sScriptedInputRanges[i].startFrame && frame <= sScriptedInputRanges[i].endFrame)
                pressedMask |= sScriptedInputRanges[i].pressedMask;
        }
    }

    pressedMask |= ComputeAutoPlayOakInput(frame);
    pressedMask |= ComputeAutoPlayContinueInput(frame);

    /* Only override REG_KEYINPUT when scripted/autoplay input is active.
     * Otherwise, preserve the keyboard state set by PollInput(). */
    if (pressedMask != 0)
        REG_KEYINPUT &= ~pressedMask;
}

static void RequestSnapshot(const char *label)
{
    if (sFastModeEnabled && !sTraceNamingFramesEnabled && !sTraceOverworldStartupEnabled)
        return;

    snprintf(sSnapshotLabel, sizeof(sSnapshotLabel), "%.95s", label);
    sSnapshotRequested = TRUE;
}

static void SanitizeSnapshotLabel(char *label)
{
    size_t i;

    for (i = 0; label[i] != '\0'; i++)
    {
        char c = label[i];

        if (!((c >= 'a' && c <= 'z')
           || (c >= 'A' && c <= 'Z')
           || (c >= '0' && c <= '9')
           || c == '_' || c == '-'))
        {
            label[i] = '_';
        }
    }
}

static void DumpCurrentFramebuffer(u32 frame, const char *label)
{
    char safeLabel[96];
    char path[192];
    const u32 *fb = HostRendererGetFramebuffer();
    FILE *f;
    int i;

    snprintf(safeLabel, sizeof(safeLabel), "%s", label);
    SanitizeSnapshotLabel(safeLabel);
    snprintf(path, sizeof(path), "pfr_play_frames/%06u_%s.ppm", frame, safeLabel);

    f = fopen(path, "wb");
    if (f == NULL)
        return;

    fprintf(f, "P6\n%d %d\n255\n", GBA_SCREEN_WIDTH, GBA_SCREEN_HEIGHT);
    for (i = 0; i < GBA_SCREEN_WIDTH * GBA_SCREEN_HEIGHT; i++)
    {
        u32 pixel = fb[i];
        u8 rgb[3];

        rgb[0] = (pixel >> 16) & 0xFF;
        rgb[1] = (pixel >> 8) & 0xFF;
        rgb[2] = pixel & 0xFF;
        fwrite(rgb, 1, 3, f);
    }

    fclose(f);
}

static u32 CountNonZeroWords(const void *data, size_t size)
{
    const u32 *words = data;
    size_t count = size / sizeof(u32);
    u32 nonZero = 0;
    size_t i;

    for (i = 0; i < count; i++)
    {
        if (words[i] != 0)
            nonZero++;
    }

    return nonZero;
}

static u32 CountSampledNonBlackPixels(void)
{
    const u32 *framebuffer = HostRendererGetFramebuffer();
    u32 nonBlack = 0;
    int i;

    for (i = 0; i < GBA_SCREEN_WIDTH * GBA_SCREEN_HEIGHT; i += 32)
    {
        if ((framebuffer[i] & 0x00FFFFFF) != 0)
            nonBlack++;
    }

    return nonBlack;
}

static void FormatActiveTasks(char *buffer, size_t size)
{
    size_t used = 0;
    int i;

    used += snprintf(buffer + used, size - used, "tasks=");
    for (i = 0; i < NUM_TASKS && used + 1 < size; i++)
    {
        if (!gTasks[i].isActive)
            continue;

        used += snprintf(buffer + used, size - used,
                         "%s%d:%s(d0=%d)",
                         (used > 6) ? " " : "",
                         i,
                         CallbackName((MainCallback)gTasks[i].func),
                         gTasks[i].data[0]);
    }
}

static void TraceOverworldStartupState(u32 frame)
{
    char buffer[512];
    u32 delta = frame - sTraceOverworldStartupFrame;
    u32 plttNonZero = CountNonZeroWords((const void *)PLTT, PLTT_SIZE);
    u32 unfadedNonZero = CountNonZeroWords(gPlttBufferUnfaded, PLTT_SIZE);
    u32 fadedNonZero = CountNonZeroWords(gPlttBufferFaded, PLTT_SIZE);
    u32 sampledNonBlack = CountSampledNonBlackPixels();

    snprintf(buffer, sizeof(buffer),
             "overworld_startup delta=%u fade(active=%u mode=%u y=%u target=%u bufDis=%u) "
             "weather(state=%u ready=%u fadeIn=%u cur=%u next=%u) "
             "palette(pltt=%u unfaded=%u faded=%u) framebuffer(sampledNonBlack=%u)",
             delta,
             gPaletteFade.active,
             gPaletteFade.mode,
             gPaletteFade.y,
             gPaletteFade.targetY,
             gPaletteFade.bufferTransferDisabled,
             gWeatherPtr->palProcessingState,
             gWeatherPtr->readyForInit,
             gWeatherPtr->fadeInActive,
             gWeatherPtr->currWeather,
             gWeatherPtr->nextWeather,
             plttNonZero,
             unfadedNonZero,
             fadedNonZero,
             sampledNonBlack);
    TraceLog(frame, buffer);

    FormatActiveTasks(buffer, sizeof(buffer));
    TraceLog(frame, buffer);
}

static bool8 ShouldDumpOverworldStartupFrame(u32 delta)
{
    return delta == 0
        || delta == 1
        || delta == 2
        || delta == 4
        || delta == 8
        || delta == 16
        || delta == 32
        || delta == 64
        || delta == 128
        || delta == 256
        || delta == 512;
}

static void TraceOverworldStartup(u32 frame)
{
    char label[64];
    u32 delta;
    u32 sampledNonBlack;
    const char *cb2Name = CallbackName(gMain.callback2);

    if (!sTraceOverworldStartupEnabled)
        return;
    if (sTraceOverworldStartupCompleted)
        return;

    if (!sTraceOverworldStartupActive)
    {
        if (gMain.callback1 == CB1_Overworld
         && strcmp(cb2Name, "CB2_Overworld") == 0)
        {
            sTraceOverworldStartupActive = TRUE;
            sTraceOverworldStartupFrame = frame;
            sTraceOverworldFirstVisibleLogged = FALSE;
            TraceLog(frame, "overworld_startup tracing activated");
        }
        else
        {
            return;
        }
    }

    delta = frame - sTraceOverworldStartupFrame;
    if (delta > 900)
    {
        TraceLog(frame, "overworld_startup tracing finished without visible framebuffer sample");
        sTraceOverworldStartupActive = FALSE;
        sTraceOverworldStartupCompleted = TRUE;
        return;
    }

    if ((delta & 7) == 0 || ShouldDumpOverworldStartupFrame(delta))
        TraceOverworldStartupState(frame);

    if (ShouldDumpOverworldStartupFrame(delta))
    {
        snprintf(label, sizeof(label), "overworld_startup_%03u", delta);
        TraceGpuState(frame, label);
        DumpCurrentFramebuffer(frame, label);
    }

    sampledNonBlack = CountSampledNonBlackPixels();
    if (!sTraceOverworldFirstVisibleLogged && sampledNonBlack != 0)
    {
        sTraceOverworldFirstVisibleLogged = TRUE;
        snprintf(label, sizeof(label), "overworld_visible_%03u", delta);
        TraceLog(frame, "overworld_startup first non-black framebuffer sample detected");
        TraceGpuState(frame, label);
        DumpCurrentFramebuffer(frame, label);
        sTraceOverworldStartupActive = FALSE;
        sTraceOverworldStartupCompleted = TRUE;
    }
}

static void TraceGpuState(u32 frame, const char *label)
{
    char buffer[256];
    u16 dispcnt = GetGpuReg(REG_OFFSET_DISPCNT);
    u16 bg0cnt = GetGpuReg(REG_OFFSET_BG0CNT);
    u16 bg1cnt = GetGpuReg(REG_OFFSET_BG1CNT);
    u16 bg2cnt = GetGpuReg(REG_OFFSET_BG2CNT);
    u16 bg3cnt = GetGpuReg(REG_OFFSET_BG3CNT);
    u16 bldcnt = GetGpuReg(REG_OFFSET_BLDCNT);
    u16 bldalpha = GetGpuReg(REG_OFFSET_BLDALPHA);
    u16 bldy = GetGpuReg(REG_OFFSET_BLDY);
    u16 winin = GetGpuReg(REG_OFFSET_WININ);
    u16 winout = GetGpuReg(REG_OFFSET_WINOUT);
    u16 bg0hofs = GetGpuReg(REG_OFFSET_BG0HOFS);
    u16 bg0vofs = GetGpuReg(REG_OFFSET_BG0VOFS);
    u16 bg1hofs = GetGpuReg(REG_OFFSET_BG1HOFS);
    u16 bg1vofs = GetGpuReg(REG_OFFSET_BG1VOFS);
    u16 bg2hofs = GetGpuReg(REG_OFFSET_BG2HOFS);
    u16 bg2vofs = GetGpuReg(REG_OFFSET_BG2VOFS);
    u32 plttNonZero = CountNonZeroWords((const void *)PLTT, PLTT_SIZE);
    u32 vramNonZero = CountNonZeroWords((const void *)VRAM, VRAM_SIZE);
    u32 oamNonZero = CountNonZeroWords((const void *)OAM, OAM_SIZE);
    const u16 *pltt = (const u16 *)PLTT;

    snprintf(buffer, sizeof(buffer),
             "%s gpu DISPCNT=0x%04X BG0=0x%04X BG1=0x%04X BG2=0x%04X BG3=0x%04X BLDCNT=0x%04X BLDALPHA=0x%04X BLDY=0x%04X WININ=0x%04X WINOUT=0x%04X",
             label, dispcnt, bg0cnt, bg1cnt, bg2cnt, bg3cnt, bldcnt, bldalpha, bldy, winin, winout);
    TraceLog(frame, buffer);

    snprintf(buffer, sizeof(buffer),
             "%s scroll BG0=(%u,%u) BG1=(%u,%u) BG2=(%u,%u) PLTT[0..3]=%04X,%04X,%04X,%04X nonZeroWords pltt=%u vram=%u oam=%u",
             label,
             bg0hofs, bg0vofs,
             bg1hofs, bg1vofs,
             bg2hofs, bg2vofs,
             pltt[0], pltt[1], pltt[2], pltt[3],
             plttNonZero, vramNonZero, oamNonZero);
    TraceLog(frame, buffer);
}

static void TraceLog(u32 frame, const char *message)
{
    if (sTraceFile != NULL)
    {
        fprintf(sTraceFile, "[%06u] %s\n", frame, message);
        fflush(sTraceFile);
    }
    fprintf(stderr, "[%06u] %s\n", frame, message);
}

/* ---- ELF symbol table lookup for callback tracing ---- */

struct SymEntry {
    uintptr_t addr;
    const char *name;
};

static struct SymEntry *sSymTable = NULL;
static int sSymCount = 0;

static int SymEntryCmp(const void *a, const void *b)
{
    uintptr_t aa = ((const struct SymEntry *)a)->addr;
    uintptr_t bb = ((const struct SymEntry *)b)->addr;
    return (aa > bb) - (aa < bb);
}

/* Build a sorted symbol table from `nm /proc/self/exe` at startup.
 * This captures ALL symbols including static (local) functions,
 * so every callback pointer resolves to a human-readable name. */
/* Use libc allocators directly — the game overrides malloc with its
 * own heap allocator that operates on gHeap, which isn't set up yet
 * when InitSymbolTable runs (and would corrupt the game heap). */
extern void *__libc_malloc(size_t);
extern void *__libc_realloc(void *, size_t);
extern void __libc_free(void *);

static char *sys_strdup(const char *s)
{
    size_t len = strlen(s) + 1;
    char *d = __libc_malloc(len);
    if (d) memcpy(d, s, len);
    return d;
}

static void InitSymbolTable(void)
{
    FILE *fp;
    char line[512];
    int capacity = 4096;

    sSymTable = __libc_malloc(capacity * sizeof(struct SymEntry));
    sSymCount = 0;
    if (!sSymTable)
        return;

    /* readlink /proc/self/exe to get the actual binary path,
     * then run nm on it to get all symbols including static ones. */
    char exe_path[1024];
    ssize_t len = readlink("/proc/self/exe", exe_path, sizeof(exe_path) - 1);
    if (len <= 0) return;
    exe_path[len] = 0;
    char cmd[1200];
    snprintf(cmd, sizeof(cmd), "nm -n %s 2>/dev/null", exe_path);
    fp = popen(cmd, "r");
    if (!fp) { __libc_free(sSymTable); sSymTable = NULL; return; }

    while (fgets(line, sizeof(line), fp))
    {
        uintptr_t addr;
        char type;
        char name[256];
        if (sscanf(line, "%lx %c %255s", &addr, &type, name) != 3)
            continue;
        if (type != 't' && type != 'T')
            continue;
        if (sSymCount >= capacity) {
            capacity *= 2;
            sSymTable = __libc_realloc(sSymTable, capacity * sizeof(struct SymEntry));
            if (!sSymTable) { sSymCount = 0; pclose(fp); return; }
        }
        sSymTable[sSymCount].addr = addr;
        sSymTable[sSymCount].name = sys_strdup(name);
        sSymCount++;
    }
    pclose(fp);
    qsort(sSymTable, sSymCount, sizeof(struct SymEntry), SymEntryCmp);
}

static const char *CallbackName(MainCallback callback)
{
    static char addr_buf[64];

    if (callback == NULL)
        return "NULL";

    /* Binary search the symbol table for an exact match */
    uintptr_t target = (uintptr_t)callback;
    int lo = 0, hi = sSymCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (sSymTable[mid].addr == target)
            return sSymTable[mid].name;
        else if (sSymTable[mid].addr < target)
            lo = mid + 1;
        else
            hi = mid - 1;
    }

    snprintf(addr_buf, sizeof(addr_buf), "0x%lx",
             (unsigned long)(uintptr_t)callback);
    return addr_buf;
}

/* OakPlaceholderName removed — StringExpandPlaceholders now from upstream */

static void TraceCallbackChange(u32 frame, const char *label, MainCallback callback)
{
    char buffer[160];

    snprintf(buffer, sizeof(buffer), "%s -> %s (%p)", label, CallbackName(callback), (void *)callback);
    TraceLog(frame, buffer);
    RequestSnapshot(buffer);
}

static void TraceInput(u32 frame)
{
    char buffer[128];

    if (sFastModeEnabled)
        return;

    if (gMain.newKeys == 0)
        return;

    snprintf(buffer, sizeof(buffer),
             "input newKeys=0x%04X heldKeys=0x%04X callback2=%s",
             gMain.newKeys,
             gMain.heldKeys,
             CallbackName(gMain.callback2));
    TraceLog(frame, buffer);
}

static void TraceMilestones(u32 frame)
{
    char buffer[160];

    if (gMain.callback1 != sLastCallback1)
    {
        sLastCallback1 = gMain.callback1;
        TraceCallbackChange(frame, "callback1", gMain.callback1);
    }

    if (gMain.callback2 != sLastCallback2)
    {
        sLastCallback2 = gMain.callback2;
        TraceCallbackChange(frame, "callback2", gMain.callback2);
    }

    if (gHostTitleStubCB2InitMainMenuCalls != sLastMainMenuInitCalls)
    {
        sLastMainMenuInitCalls = gHostTitleStubCB2InitMainMenuCalls;
        snprintf(buffer, sizeof(buffer), "main menu init calls=%u", sLastMainMenuInitCalls);
        TraceLog(frame, buffer);
        RequestSnapshot("main_menu_init");
    }

    if (gHostTitleStubStartNewGameSceneCalls != sLastStartNewGameSceneCalls)
    {
        sLastStartNewGameSceneCalls = gHostTitleStubStartNewGameSceneCalls;
        snprintf(buffer, sizeof(buffer), "StartNewGameScene calls=%u", sLastStartNewGameSceneCalls);
        TraceLog(frame, buffer);
        RequestSnapshot("start_new_game_scene");
    }

    if (gHostOakSpeechControlsGuidePage1Loads != sLastControlsGuidePage1Loads)
    {
        sLastControlsGuidePage1Loads = gHostOakSpeechControlsGuidePage1Loads;
        TraceLog(frame, "Oak controls guide page 1 reached");
        RequestSnapshot("oak_controls_page_1");
    }
    if (gHostOakSpeechControlsGuidePage2Loads != sLastControlsGuidePage2Loads)
    {
        sLastControlsGuidePage2Loads = gHostOakSpeechControlsGuidePage2Loads;
        TraceLog(frame, "Oak controls guide page 2 reached");
        RequestSnapshot("oak_controls_page_2");
    }
    if (gHostOakSpeechControlsGuidePage3Loads != sLastControlsGuidePage3Loads)
    {
        sLastControlsGuidePage3Loads = gHostOakSpeechControlsGuidePage3Loads;
        TraceLog(frame, "Oak controls guide page 3 reached");
        RequestSnapshot("oak_controls_page_3");
    }
    if (gHostOakSpeechPikachuIntroPage1Loads != sLastPikachuIntroPage1Loads)
    {
        sLastPikachuIntroPage1Loads = gHostOakSpeechPikachuIntroPage1Loads;
        TraceLog(frame, "Oak Pikachu intro page 1 reached");
        RequestSnapshot("oak_pikachu_intro_1");
    }
    if (gHostOakSpeechPikachuIntroPage2Loads != sLastPikachuIntroPage2Loads)
    {
        sLastPikachuIntroPage2Loads = gHostOakSpeechPikachuIntroPage2Loads;
        TraceLog(frame, "Oak Pikachu intro page 2 reached");
        RequestSnapshot("oak_pikachu_intro_2");
    }
    if (gHostOakSpeechPikachuIntroPage3Loads != sLastPikachuIntroPage3Loads)
    {
        sLastPikachuIntroPage3Loads = gHostOakSpeechPikachuIntroPage3Loads;
        TraceLog(frame, "Oak Pikachu intro page 3 reached");
        RequestSnapshot("oak_pikachu_intro_3");
    }
    if (gHostOakSpeechWelcomeToTheWorldPrints != sLastWelcomePrints)
    {
        sLastWelcomePrints = gHostOakSpeechWelcomeToTheWorldPrints;
        TraceLog(frame, "Oak welcome message printed");
        RequestSnapshot("oak_welcome_message");
    }
    if (gHostOakSpeechThisWorldPrints != sLastThisWorldPrints)
    {
        sLastThisWorldPrints = gHostOakSpeechThisWorldPrints;
        TraceLog(frame, "Oak 'This world' message printed");
        RequestSnapshot("oak_this_world_message");
    }
    if (gHostOakSpeechIStudyPokemonPrints != sLastIStudyPokemonPrints)
    {
        sLastIStudyPokemonPrints = gHostOakSpeechIStudyPokemonPrints;
        TraceLog(frame, "Oak 'I study Pokemon' message printed");
        RequestSnapshot("oak_i_study_pokemon");
    }
    if (gHostOakSpeechAskPlayerGenderPrints != sLastAskPlayerGenderPrints)
    {
        sLastAskPlayerGenderPrints = gHostOakSpeechAskPlayerGenderPrints;
        TraceLog(frame, "Oak player gender prompt printed");
        RequestSnapshot("oak_ask_player_gender");
    }

    /* StringExpandPlaceholders and CB2_NewGame now from upstream —
       placeholder source tracking removed */

    if (gHostOakSpeechDoNamingScreenCalls != sLastNamingCalls)
    {
        sLastNamingCalls = gHostOakSpeechDoNamingScreenCalls;
        snprintf(buffer, sizeof(buffer), "Oak naming screen calls=%u", sLastNamingCalls);
        TraceLog(frame, buffer);
        RequestSnapshot("oak_naming_screen");
    }
}

static void TraceFramebufferUniformity(u32 frame)
{
    const u32 *framebuffer;
    u32 first;
    u32 sameCount = 1;
    int i;

    if (sFastModeEnabled)
        return;

    framebuffer = HostRendererGetFramebuffer();
    first = framebuffer[0];
    for (i = 64; i < GBA_SCREEN_WIDTH * GBA_SCREEN_HEIGHT; i += 64)
    {
        if (framebuffer[i] == first)
            sameCount++;
    }

    if (sameCount >= 590)
    {
        if (sUniformFrameRunLength == 0 || sLastUniformColor != first)
        {
            sUniformFrameRunLength = 1;
            sLastUniformColor = first;
        }
        else
        {
            sUniformFrameRunLength++;
        }

        if (sUniformFrameRunLength == 120)
        {
            char buffer[160];

            snprintf(buffer, sizeof(buffer),
                     "framebuffer nearly uniform for 120 frames, color=0x%08X callback2=%s",
                     sLastUniformColor,
                     CallbackName(gMain.callback2));
            TraceLog(frame, buffer);
            RequestSnapshot("uniform_frame_warning");
        }
    }
    else
    {
        sUniformFrameRunLength = 0;
    }
}

static double sVBAccCb = 0, sVBAccGpu = 0, sVBAccDma = 0, sVBAccAudio = 0, sVBAccOther = 0;
static unsigned long sVBCount = 0;

static void PlayVBlankHandler(void)
{
    extern u16 Random(void);
    struct timespec _ts;
    double va, vb, vc, vd, ve, vf;

    clock_gettime(CLOCK_MONOTONIC, &_ts); va = _ts.tv_sec * 1e9 + _ts.tv_nsec;
    if (gMain.vblankCounter1)
        (*gMain.vblankCounter1)++;
    if (gMain.vblankCallback)
        gMain.vblankCallback();
    clock_gettime(CLOCK_MONOTONIC, &_ts); vb = _ts.tv_sec * 1e9 + _ts.tv_nsec;

    gMain.vblankCounter2++;
    CopyBufferedValuesToGpuRegs();
    clock_gettime(CLOCK_MONOTONIC, &_ts); vc = _ts.tv_sec * 1e9 + _ts.tv_nsec;

    ProcessDma3Requests();
    clock_gettime(CLOCK_MONOTONIC, &_ts); vd = _ts.tv_sec * 1e9 + _ts.tv_nsec;

    HostAudioMixAndPush();
    clock_gettime(CLOCK_MONOTONIC, &_ts); ve = _ts.tv_sec * 1e9 + _ts.tv_nsec;

    Random();
    INTR_CHECK |= INTR_FLAG_VBLANK;
    gMain.intrCheck |= INTR_FLAG_VBLANK;
    clock_gettime(CLOCK_MONOTONIC, &_ts); vf = _ts.tv_sec * 1e9 + _ts.tv_nsec;

    sVBAccCb    += (vb - va);
    sVBAccGpu   += (vc - vb);
    sVBAccDma   += (vd - vc);
    sVBAccAudio += (ve - vd);
    sVBAccOther += (vf - ve);
    sVBCount++;

    if (sVBCount % 60000 == 0) {
        double tot = sVBAccCb + sVBAccGpu + sVBAccDma + sVBAccAudio + sVBAccOther;
        fprintf(stderr, "VB_PROF n=%lu cb=%.0fns(%.1f%%) gpu=%.0fns(%.1f%%) dma=%.0fns(%.1f%%) audio=%.0fns(%.1f%%) other=%.0fns(%.1f%%)\n",
            sVBCount,
            sVBAccCb/sVBCount, 100.0*sVBAccCb/tot,
            sVBAccGpu/sVBCount, 100.0*sVBAccGpu/tot,
            sVBAccDma/sVBCount, 100.0*sVBAccDma/tot,
            sVBAccAudio/sVBCount, 100.0*sVBAccAudio/tot,
            sVBAccOther/sVBCount, 100.0*sVBAccOther/tot);
    }
}

static void PlayHBlankHandler(void)
{
    if (gMain.hblankCallback)
        gMain.hblankCallback();
    gMain.intrCheck |= INTR_FLAG_HBLANK;
}

static void IntrDummy(void) { }

/* ── Key reading (mirrors main.c's static ReadKeys) ────────── */

/* Not exported in main.h but defined in main.c, set by InitKeys() */
extern u16 gKeyRepeatContinueDelay;

static void PlayReadKeys(void)
{
    u16 keyInput = REG_KEYINPUT ^ KEYS_MASK;

    gMain.newKeysRaw = keyInput & ~gMain.heldKeysRaw;
    gMain.newKeys = gMain.newKeysRaw;
    gMain.newAndRepeatedKeys = gMain.newKeysRaw;

    if (keyInput != 0 && gMain.heldKeys == keyInput)
    {
        gMain.keyRepeatCounter--;
        if (gMain.keyRepeatCounter == 0)
        {
            gMain.newAndRepeatedKeys = keyInput;
            gMain.keyRepeatCounter = gKeyRepeatContinueDelay;
        }
    }
    else
    {
        gMain.keyRepeatCounter = gKeyRepeatStartDelay;
    }

    gMain.heldKeysRaw = keyInput;
    gMain.heldKeys = gMain.heldKeysRaw;

    if (gSaveBlock2Ptr->optionsButtonMode == OPTIONS_BUTTON_MODE_L_EQUALS_A)
    {
        if (JOY_NEW(L_BUTTON))
            gMain.newKeys |= A_BUTTON;
        if (JOY_HELD(L_BUTTON))
            gMain.heldKeys |= A_BUTTON;
    }

    if (JOY_NEW(gMain.watchedKeysMask))
        gMain.watchedKeysPressed = TRUE;

    /* Auto-repeat A and B while held — injects into both newKeys and
     * newAndRepeatedKeys so JOY_NEW() and JOY_REPT() both see repeats.
     * This makes text advancement, dialog, and overworld interaction
     * fast without needing to physically mash the button. */
    if ((gMain.heldKeys & A_BUTTON) && !(gMain.newKeys & A_BUTTON))
    {
        static u8 sARepeatTimer = 0;
        if (++sARepeatTimer >= 4)
        {
            gMain.newKeys |= A_BUTTON;
            gMain.newAndRepeatedKeys |= A_BUTTON;
            sARepeatTimer = 0;
        }
    }
    if ((gMain.heldKeys & B_BUTTON) && !(gMain.newKeys & B_BUTTON))
    {
        static u8 sBRepeatTimer = 0;
        if (++sBRepeatTimer >= 4)
        {
            gMain.newKeys |= B_BUTTON;
            gMain.newAndRepeatedKeys |= B_BUTTON;
            sBRepeatTimer = 0;
        }
    }
}

/* ── Frame simulation ──────────────────────────────────────── */

struct PlayFrameContext
{
    u32 frame;
};

static void PlayFrameLogic(void *userdata)
{
    const struct PlayFrameContext *ctx = userdata;
    u32 frame = ctx->frame;
    bool8 traceDetailed = ShouldTraceDetailedFrame(frame);
    char buffer[256];

    ApplyScriptedInput(frame);
    PlayReadKeys();
    TraceInput(frame);
    TraceMilestones(frame);

    if (traceDetailed)
    {
        snprintf(buffer, sizeof(buffer),
                 "frame_detail begin cb1=%s cb2=%s state=%u tasks=%u vblank=%s",
                 CallbackName(gMain.callback1),
                 CallbackName(gMain.callback2),
                 gMain.state,
                 GetTaskCount(),
                 CallbackName(gMain.vblankCallback));
        TraceLog(frame, buffer);
    }

    if (gMain.callback1)
    {
        if (traceDetailed)
            TraceLog(frame, "frame_detail before callback1");
        gMain.callback1();
        if (traceDetailed)
            TraceLog(frame, "frame_detail after callback1");
    }
    if (gMain.callback2)
    {
        if (traceDetailed)
            TraceLog(frame, "frame_detail before callback2");
        gMain.callback2();
        if (traceDetailed)
            TraceLog(frame, "frame_detail after callback2");
    }

    if (traceDetailed)
        TraceLog(frame, "frame_detail before PlayTimeCounter_Update");
    PlayTimeCounter_Update();
    if (traceDetailed)
        TraceLog(frame, "frame_detail after PlayTimeCounter_Update");

    if (traceDetailed)
        TraceLog(frame, "frame_detail before MapMusicMain");
    MapMusicMain();
    if (traceDetailed)
        TraceLog(frame, "frame_detail after MapMusicMain");
}


/* ── RL Action Boundary Instrumentation ──────────────────── */

static bool8 sRlInstrumentEnabled = FALSE;
static u32 sRlFramesSinceReady = 0;
static bool8 sRlWasReady = FALSE;
static u32 sRlActionCount = 0;
static FILE *sRlInstrumentLog = NULL;

static const char *GetGameModeName(void)
{
    if (gMain.callback1 == CB1_Overworld)
        return "overworld";
    if (gMain.callback2 == BattleMainCB2)
        return "battle";
    if (gMain.inBattle)
        return "battle_other";
    return "other";
}

static bool8 PlayerReadyCheck(void)
{
    /* Overworld mode: callback1 == CB1_Overworld */
    if (gMain.callback1 == CB1_Overworld)
    {
        /* Text printer waiting for A/B? That is an action point. */
        /* We check via script lock + tile state */
        if (!ArePlayerFieldControlsLocked()
            && (gPlayerAvatar.tileTransitionState == T_NOT_MOVING
             || gPlayerAvatar.tileTransitionState == T_TILE_CENTER)
            && !ObjectEventIsMovementOverridden(
                   &gObjectEvents[gPlayerAvatar.objectEventId]))
            return TRUE;
        
        /* Script is running but text is waiting for player A/B press. */
        /* We detect this by checking if field controls are locked but */
        /* newKeys would be consumed by WaitForAorBPress.             */
        /* For now, we check if ScriptContext is in WAITING state AND  */
        /* no movement is happening — meaning dialog is up.           */
        if (ArePlayerFieldControlsLocked()
            && gPlayerAvatar.tileTransitionState != T_TILE_TRANSITION)
        {
            /* Could be dialog wait, menu wait, or cutscene in progress. */
            /* Log this as a sub-state for analysis. */
        }
        return FALSE;
    }
    
    /* Battle mode: callback2 == BattleMainCB2 */
    if (gMain.callback2 == BattleMainCB2)
    {
        /* Controllers all done = waiting for player input */
        if (gBattleControllerExecFlags == 0)
            return TRUE;
        return FALSE;
    }
    
    /* Other modes (menus, etc) — always accepting input */
    if (gMain.inBattle)
        return FALSE; /* battle transition, not ready yet */
    
    return FALSE; /* unknown state, be conservative */
}

static void RlInstrumentFrame(void)
{
    bool8 ready;
    
    if (!sRlInstrumentEnabled)
        return;
    
    ready = PlayerReadyCheck();
    sRlFramesSinceReady++;
    
    if (ready && !sRlWasReady)
    {
        /* Transition: not-ready → ready = action boundary reached */
        if (sRlInstrumentLog)
        {
            fprintf(sRlInstrumentLog,
                "action=%u frames=%u mode=%s cb2=%p tileState=%u locked=%u battleExec=%u frame=%u\n",
                sRlActionCount,
                sRlFramesSinceReady,
                GetGameModeName(),
                (void *)gMain.callback2,
                (unsigned)gPlayerAvatar.tileTransitionState,
                (unsigned)ArePlayerFieldControlsLocked(),
                (unsigned)gBattleControllerExecFlags,
                sEmulatedFrameCount);
            fflush(sRlInstrumentLog);
        }
        sRlActionCount++;
        sRlFramesSinceReady = 0;
    }
    else if (!ready && sRlWasReady)
    {
        /* Transition: ready → not-ready = player took an action */
        if (sRlInstrumentLog)
        {
            fprintf(sRlInstrumentLog,
                "ACTION_START action=%u mode=%s idle_frames=%u frame=%u\n",
                sRlActionCount,
                GetGameModeName(),
                sRlFramesSinceReady,
                sEmulatedFrameCount);
            fflush(sRlInstrumentLog);
        }
        sRlFramesSinceReady = 0;
    }
    
    sRlWasReady = ready;
}

static void StepFrame(bool8 renderFrame)
{
    struct PlayFrameContext ctx = { .frame = sEmulatedFrameCount };

    if (renderFrame)
        HostFrameStepRun(PlayFrameLogic, &ctx, TRUE);
    else
        HostFrameStepRunFast(PlayFrameLogic, &ctx);

    sEmulatedFrameCount++;
    RlInstrumentFrame();
}

/* ── Main ──────────────────────────────────────────────────── */

static void crash_handler(int sig, siginfo_t *info, void *ucontext)
{
    void *frames[32];
    int logFd;
    int n = backtrace(frames, 32);
    fprintf(stderr, "\n=== CRASH: signal %d (%s) fault_addr=%p si_code=%d ===\n", sig, sig==11?"SIGSEGV":sig==7?"SIGBUS":"other", info->si_addr, info->si_code);
    backtrace_symbols_fd(frames, n, STDERR_FILENO);
    logFd = HostLogGetFd();
    if (logFd >= 0 && logFd != STDERR_FILENO)
    {
        dprintf(logFd, "\n=== CRASH: signal %d ===\n", sig);
        backtrace_symbols_fd(frames, n, logFd);
        fsync(logFd);
    }
    _exit(128 + sig);
}

int main(int argc, char *argv[])
{
    struct timespec benchmarkStartTime;
    struct timespec benchmarkEndTime;
    bool8 benchmarkClockStarted = FALSE;
    bool8 benchmarkClockStopped = FALSE;
    double benchmarkElapsedSeconds = 0.0;

    {
        struct sigaction sa;
        memset(&sa, 0, sizeof(sa));
        sa.sa_sigaction = crash_handler;
        sa.sa_flags = SA_SIGINFO;
        sigaction(SIGSEGV, &sa, NULL);
        sigaction(SIGBUS, &sa, NULL);
        sigaction(SIGABRT, &sa, NULL);
    }

    int i;
    int argi;
    const char *scriptPath = NULL;
    const char *autoPlayOak = getenv("PFR_AUTOPLAY_OAK_NEWGAME");
    const char *traceNamingFrames = getenv("PFR_TRACE_NAMING_FRAMES");
    const char *traceOverworldStartup = getenv("PFR_TRACE_OVERWORLD_STARTUP");

    sAutoPlayOakNewGameEnabled = (autoPlayOak != NULL
                               && autoPlayOak[0] != '\0'
                               && strcmp(autoPlayOak, "0") != 0);
    sTraceNamingFramesEnabled = (traceNamingFrames != NULL
                              && traceNamingFrames[0] != '\0'
                              && strcmp(traceNamingFrames, "0") != 0);
    sTraceOverworldStartupEnabled = (traceOverworldStartup != NULL
                                  && traceOverworldStartup[0] != '\0'
                                  && strcmp(traceOverworldStartup, "0") != 0);
    const char *debugGiveStarter = getenv("PFR_DEBUG_GIVE_STARTER");
    sDebugGiveStarterEnabled = (debugGiveStarter != NULL
                             && debugGiveStarter[0] != '\0'
                             && strcmp(debugGiveStarter, "0") != 0);
    ResetAutoPlayOakState();
    sTraceOverworldStartupActive = FALSE;
    sTraceOverworldStartupCompleted = FALSE;
    sTraceOverworldFirstVisibleLogged = FALSE;
    sTraceOverworldStartupFrame = 0;
    sProgramArgv = argv;
    SetPathOption(sActiveSavePath, sizeof(sActiveSavePath), getenv("PFR_SAVE_PATH"), "pokefirered.sav");
    SetPathOption(sBootLoadSavePath, sizeof(sBootLoadSavePath), getenv("PFR_LOAD_SAVE"), NULL);
    SetPathOption(sSnapshotDir, sizeof(sSnapshotDir), getenv("PFR_SNAPSHOT_DIR"), "pfr_debug_saves");
    SetPathOption(sStateDir, sizeof(sStateDir), getenv("PFR_STATE_DIR"), "pfr_debug_states");
    SetPathOption(sQuickLoadPath, sizeof(sQuickLoadPath), getenv("PFR_QUICKLOAD_PATH"), NULL);
    SetPathOption(sControlFilePath, sizeof(sControlFilePath), getenv("PFR_CONTROL_FILE"), NULL);
    sAutoPlayContinueEnabled = FlagEnabled(getenv("PFR_AUTOPLAY_CONTINUE"));
    sDisableAudioEnabled = FlagEnabled(getenv("PFR_DISABLE_AUDIO"));
    if (scriptPath == NULL)
        scriptPath = getenv("PFR_INPUT_SCRIPT");

    for (argi = 1; argi < argc; argi++)
    {
        if (strcmp(argv[argi], "--input") == 0 && argi + 1 < argc)
        {
            scriptPath = argv[++argi];
        }
        else if (strcmp(argv[argi], "--save-path") == 0 && argi + 1 < argc)
        {
            SetPathOption(sActiveSavePath, sizeof(sActiveSavePath), argv[++argi], NULL);
        }
        else if (strcmp(argv[argi], "--load-save") == 0 && argi + 1 < argc)
        {
            SetPathOption(sBootLoadSavePath, sizeof(sBootLoadSavePath), argv[++argi], NULL);
        }
        else if (strcmp(argv[argi], "--snapshot-dir") == 0 && argi + 1 < argc)
        {
            SetPathOption(sSnapshotDir, sizeof(sSnapshotDir), argv[++argi], NULL);
        }
        else if (strcmp(argv[argi], "--state-dir") == 0 && argi + 1 < argc)
        {
            SetPathOption(sStateDir, sizeof(sStateDir), argv[++argi], NULL);
        }
        else if (strcmp(argv[argi], "--quickload-path") == 0 && argi + 1 < argc)
        {
            SetPathOption(sQuickLoadPath, sizeof(sQuickLoadPath), argv[++argi], NULL);
        }
        else if (strcmp(argv[argi], "--control-file") == 0 && argi + 1 < argc)
        {
            SetPathOption(sControlFilePath, sizeof(sControlFilePath), argv[++argi], NULL);
        }
        else if (strcmp(argv[argi], "--headless") == 0)
        {
            setenv("PFR_HEADLESS", "1", 1);
        }
        else if (strcmp(argv[argi], "--unthrottled") == 0)
        {
            setenv("PFR_UNTHROTTLED", "1", 1);
        }
        else if (strcmp(argv[argi], "--fast-forward") == 0 && argi + 1 < argc)
        {
            u32 fastForward;

            if (!ParseU32Option(argv[argi + 1], &fastForward))
            {
                fprintf(stderr, "pfr_play: invalid fast-forward factor %s\n", argv[argi + 1]);
                return 1;
            }
            setenv("PFR_UNTHROTTLED", "1", 1);
            setenv("PFR_FAST_FORWARD_FACTOR", argv[++argi], 1);
        }
        else if (strcmp(argv[argi], "--benchmark-frames") == 0 && argi + 1 < argc)
        {
            if (!ParseU32Option(argv[argi + 1], &sBenchmarkFrameLimit) || sBenchmarkFrameLimit == 0)
            {
                fprintf(stderr, "pfr_play: invalid benchmark frame count %s\n", argv[argi + 1]);
                return 1;
            }
            sBenchmarkEnabled = TRUE;
            argi++;
        }
        else if (strcmp(argv[argi], "--mute") == 0)
        {
            sDisableAudioEnabled = TRUE;
        }
        else if (strcmp(argv[argi], "--max-speed") == 0)
        {
            setenv("PFR_HEADLESS", "1", 1);
            setenv("PFR_UNTHROTTLED", "1", 1);
            setenv("PFR_MAX_SPEED", "1", 1);
            if (getenv("PFR_FAST_FORWARD_FACTOR") == NULL)
                setenv("PFR_FAST_FORWARD_FACTOR", "4096", 1);
            sDisableAudioEnabled = TRUE;
        }
        else if (strcmp(argv[argi], "--autoplay-continue") == 0)
        {
            sAutoPlayContinueEnabled = TRUE;
        }
        else if (strcmp(argv[argi], "--autoplay-oak") == 0)
        {
            sAutoPlayOakNewGameEnabled = TRUE;
        }
        else if (strcmp(argv[argi], "--rl-instrument") == 0)
        {
            sRlInstrumentEnabled = TRUE;
            sRlInstrumentLog = fopen("rl_instrument.log", "w");
            if (!sRlInstrumentLog)
            {
                fprintf(stderr, "pfr_play: could not open rl_instrument.log\n");
                return 1;
            }
            fprintf(sRlInstrumentLog, "# RL Action Boundary Instrumentation\n");
            fprintf(sRlInstrumentLog, "# Play the game normally. Each line logs a player_ready() transition.\n");
            fflush(sRlInstrumentLog);
        }
        else if (strcmp(argv[argi], "--help") == 0)
        {
            fprintf(stderr,
                    "usage: %s [input_script] [--input path] [--save-path path] [--load-save path]\n"
                    "          [--snapshot-dir path] [--state-dir path] [--quickload-path path] [--control-file path]\n"
                    "          [--headless] [--unthrottled] [--fast-forward n] [--benchmark-frames n] [--mute] [--max-speed]\n"
                    "          [--autoplay-continue] [--autoplay-oak] [--rl-instrument]\n",
                    argv[0]);
            return 0;
        }
        else if (argv[argi][0] != '-' && scriptPath == NULL)
        {
            scriptPath = argv[argi];
        }
        else if (argv[argi][0] == '-')
        {
            fprintf(stderr, "pfr_play: unknown or incomplete option %s\n", argv[argi]);
            return 1;
        }
    }

    if (!EnsureParentDirectoryForFile(sActiveSavePath))
    {
        fprintf(stderr, "pfr_play: could not create parent directory for %s\n", sActiveSavePath);
        return 1;
    }
    if (!EnsureDirectoryPath(sSnapshotDir))
    {
        fprintf(stderr, "pfr_play: could not create snapshot dir %s\n", sSnapshotDir);
        return 1;
    }
    if (!EnsureDirectoryPath(sStateDir))
    {
        fprintf(stderr, "pfr_play: could not create state dir %s\n", sStateDir);
        return 1;
    }

    sFastModeEnabled = FlagEnabled(getenv("PFR_MAX_SPEED"));

    if (sBootLoadSavePath[0] != '\0' && !CopyFileToPath(sBootLoadSavePath, sActiveSavePath, TRUE))
    {
        fprintf(stderr, "pfr_play: failed to load save %s into %s\n", sBootLoadSavePath, sActiveSavePath);
        return 1;
    }

    /* Initialize host subsystems */
    HostMemoryInit();
    HostRendererInit();
    mkdir("pfr_play_frames", 0775);
    sTraceFile = fopen("pfr_play_trace.log", "w");
    if (sTraceFile != NULL)
    {
        setvbuf(sTraceFile, NULL, _IOLBF, 0);
        HostLogAttachFile(sTraceFile);
    }

    if (!HostDisplayInit())
    {
        HostLogPrintf("pfr_play: Failed to initialize display (SDL2 required)\n");
        return 1;
    }
    HostDisplaySetStateDir(sStateDir);

    /* Boot chain */
    HostCrt0Init();
    REG_KEYINPUT = KEYS_MASK; /* all keys released */

    /* ── AgbMain initialization sequence ── */

    InitGpuRegManager();

    /* Interrupt dispatch table */
    for (i = 0; i < 14; i++)
        gIntrTable[i] = IntrDummy;
    gIntrTable[3] = PlayHBlankHandler;
    gIntrTable[4] = PlayVBlankHandler;

    REG_IME = 1;
    REG_IE |= INTR_FLAG_VBLANK;

    InitKeys();

    /* Full native sound init: sets up SOUND_INFO_PTR, all SoundInfo fields,
     * music players, and cry players — without DMA/timer hardware writes. */
    HostNativeSoundInit();
    if (!sDisableAudioEnabled)
        HostAudioInit();
    else
        TraceLog(0, "audio disabled by debug configuration");

    EnableVCountIntrAtLine150();
    /* InitRFU() skipped: spins on rfu_waitREQComplete() waiting for
     * wireless adapter hardware response. No wireless adapter on native.
     * Single-player gameplay does not use RFU. */
    HostFlashInit(sActiveSavePath);
    CheckForFlashMemory();
    HostSavestateInit();

    /* Protect host-side resource pointers from savestate restore.
     * Savestate restore does a bulk memcpy of .data/.bss, which
     * would overwrite these with stale values from a prior session.
     * Any pointer to heap, libc, or OS resources MUST be protected. */
    HostSavestateProtectRegion(&sTraceFile, sizeof(sTraceFile));
    HostSavestateProtectRegion(&sRlInstrumentLog, sizeof(sRlInstrumentLog));
    HostSavestateProtectRegion(&sSymTable, sizeof(sSymTable));
    HostSavestateProtectRegion(&sSymCount, sizeof(sSymCount));
    HostSavestateProtectRegion(&sProgramArgv, sizeof(sProgramArgv));

    /* InitMainCallbacks is static in main.c; replicate inline: */
    gMain.vblankCounter1 = 0;
    gMain.vblankCounter2 = 0;
    gMain.callback1 = NULL;
    gMain.callback2 = NULL;
    gMain.vblankCallback = NULL;
    gMain.state = 0;
    gSaveBlock2Ptr = &gSaveBlock2;
    gSaveBlock1Ptr = &gSaveBlock1;
    gPokemonStoragePtr = &gPokemonStorage;
    gSaveBlock2.encryptionKey = 0;
    gQuestLogPlaybackState = QL_PLAYBACK_STATE_STOPPED;

    InitMapMusic();
    ClearDma3Requests();
    ResetBgs();
    InitHeap(gHeap, HEAP_SIZE);
    SetDefaultFontsPointer();

    gSoftResetDisabled = FALSE;
    gHelpSystemEnabled = FALSE;
    SetNotInSaveFailedScreen();

    gHostIntroStubLoadGameSaveResult = SAVE_STATUS_EMPTY;
    HostNewGameStubReset();
    HostOakSpeechStubReset();

    /* Patch 32-bit LE pointer fields in generated script bytecode arrays.
     * Must run before any game code that reads script pointers. */
    HostPatchBattleScriptPointers();
    HostPatchEventScriptPointers();
    HostPatchFieldEffectScriptPointers();
    HostPatchBattleAIScriptPointers();
    HostPatchBattleAnimScriptPointers();

    HostIntroStubReset();
    HostTitleScreenStubReset();
    sLastCallback1 = (MainCallback)(uintptr_t)-1;
    sLastCallback2 = (MainCallback)(uintptr_t)-1;
    sLastUniformColor = 0;
    sUniformFrameRunLength = 0;
    sScriptedInputEnabled = FALSE;
    sScriptedInputRangeCount = 0;
    InitSymbolTable();
    TraceLog(0, "pfr_play trace started");
    {
        char buffer[PATH_MAX + 64];

        snprintf(buffer, sizeof(buffer), "active save path: %s", sActiveSavePath);
        TraceLog(0, buffer);
        snprintf(buffer, sizeof(buffer), "snapshot dir: %s", sSnapshotDir);
        TraceLog(0, buffer);
        snprintf(buffer, sizeof(buffer), "state dir: %s", sStateDir);
        TraceLog(0, buffer);
        if (sBootLoadSavePath[0] != '\0')
        {
            snprintf(buffer, sizeof(buffer), "boot load save: %s", sBootLoadSavePath);
            TraceLog(0, buffer);
        }
        if (sQuickLoadPath[0] != '\0')
        {
            snprintf(buffer, sizeof(buffer), "quickload path: %s", sQuickLoadPath);
            TraceLog(0, buffer);
        }
        if (sControlFilePath[0] != '\0')
        {
            snprintf(buffer, sizeof(buffer), "control file: %s", sControlFilePath);
            TraceLog(0, buffer);
        }
        snprintf(buffer, sizeof(buffer), "fast-forward factor: %u", HostDisplayGetFastForwardFactor());
        TraceLog(0, buffer);
        if (sBenchmarkEnabled)
        {
            snprintf(buffer, sizeof(buffer), "benchmark frame limit: %u", sBenchmarkFrameLimit);
            TraceLog(0, buffer);
        }
    }
    if (sAutoPlayOakNewGameEnabled)
        TraceLog(0, "autoplay oak-newgame enabled");
    if (sAutoPlayContinueEnabled)
        TraceLog(0, "autoplay continue enabled");
    if (sTraceNamingFramesEnabled)
        TraceLog(0, "trace naming frames enabled");
    if (sTraceOverworldStartupEnabled)
        TraceLog(0, "trace overworld startup enabled");
    if (sFastModeEnabled)
        TraceLog(0, "max-speed mode enabled: heavy debug snapshots suppressed");

    if (scriptPath != NULL)
    {
        char buffer[160];

        if (!LoadScriptedInputFile(scriptPath))
            return 1;
        snprintf(buffer, sizeof(buffer),
                 "loaded scripted input file %s with %u ranges",
                 scriptPath,
                 sScriptedInputRangeCount);
        TraceLog(0, buffer);
    }

    {
        extern void CB2_InitCopyrightScreenAfterBootup(void);
        SetMainCallback2(CB2_InitCopyrightScreenAfterBootup);
    }

    /* ── Main loop ── */

    if (sBenchmarkEnabled && clock_gettime(CLOCK_MONOTONIC, &benchmarkStartTime) == 0)
        benchmarkClockStarted = TRUE;

    for (;;)
    {
        u32 burst = HostDisplayGetFastForwardFactor();
        u32 stepsThisBurst;
        u32 step;
        bool8 renderFrame = HostDisplayNeedsFrameRender();
        bool8 modalOverlayActive = HostDisplayHasModalOverlay();

        if (burst == 0)
            burst = 1;
        stepsThisBurst = burst;
        if (sBenchmarkEnabled)
        {
            u32 remainingFrames;

            if (sEmulatedFrameCount >= sBenchmarkFrameLimit)
            {
                sBenchmarkCompleted = TRUE;
                break;
            }

            remainingFrames = sBenchmarkFrameLimit - sEmulatedFrameCount;
            if (stepsThisBurst > remainingFrames)
                stepsThisBurst = remainingFrames;
        }

        if (!sPresentRestoredFramePending && !modalOverlayActive)
        {
            for (step = 0; step < stepsThisBurst; step++)
            {
                bool8 renderThisStep = renderFrame && (step + 1 == stepsThisBurst);
                StepFrame(renderThisStep);
            }
        }
        else
        {
            sPresentRestoredFramePending = FALSE;
        }

        /* HostDisplayPresent: render → present → poll input → vsync pacing.
         * Returns FALSE on ESC / window close. */
        if (!HostDisplayPresent())
            break;

        if (sBenchmarkEnabled && sEmulatedFrameCount >= sBenchmarkFrameLimit)
        {
            sBenchmarkCompleted = TRUE;
            break;
        }

        HandleHostActions(HostDisplayGetFrameCount());
        if (sRestartRequested || sShutdownRequested)
            break;

        if (sSnapshotRequested)
        {
            TraceGpuState(HostDisplayGetFrameCount(), sSnapshotLabel);
            DumpCurrentFramebuffer(HostDisplayGetFrameCount(), sSnapshotLabel);
            sSnapshotRequested = FALSE;
        }

        TraceOverworldStartup(HostDisplayGetFrameCount());

        /* Periodic snapshots at stable frames for debugging */
        if (!sFastModeEnabled)
        {
            u32 fc = HostDisplayGetFrameCount();
            if (fc % 200 == 0 && fc >= 6200 && fc <= 14000 || fc == 13100 || fc == 13200 || fc == 13300 ||
                fc == 13500 || fc == 14000 || fc == 14500 || fc == 15000 ||
                fc == 16000 || fc == 17000 || fc == 18000 || fc == 20000)
            {
                char label[32];
                snprintf(label, sizeof(label), "periodic_%u", fc);
                DumpCurrentFramebuffer(fc, label);
            }
        }

        TraceFramebufferUniformity(HostDisplayGetFrameCount());
    }

    if (sBenchmarkEnabled && benchmarkClockStarted && clock_gettime(CLOCK_MONOTONIC, &benchmarkEndTime) == 0)
    {
        benchmarkElapsedSeconds = TimespecDiffSeconds(&benchmarkStartTime, &benchmarkEndTime);
        benchmarkClockStopped = TRUE;
    }

    if (sRestartRequested && RestartSelf())
        return 0;

    HostAudioShutdown();
    HostDisplayDestroy();
    if (sTraceFile != NULL)
        fclose(sTraceFile);
    if (sBenchmarkCompleted && benchmarkClockStopped)
        PrintBenchmarkSummary(benchmarkElapsedSeconds);
    if (sBenchmarkEnabled && !sBenchmarkCompleted)
        return 1;
    return 0;
}
