#define _GNU_SOURCE
/*
 * pfr_play.c — Interactive player for pokefirered-native
 *
 * Opens an SDL2 window and runs the game's boot chain (copyright →
 * intro → title → main menu) with live keyboard input.
 *
 * Frame model: per-scanline rendering interleaved with HBlank DMA
 * and interrupt dispatch, matching real GBA hardware ordering.
 * The renderer processes one scanline at a time so that HBlank DMA
 * register changes (e.g. scanline scroll effects) are visible to
 * the next scanline.  HostDisplayPresent() handles display, input
 * polling, and 60 Hz frame pacing via VSYNC.
 *
 * Keyboard mapping (defined in host_display.c):
 *   Z=A  X=B  RShift=Select  Enter=Start
 *   Arrows=D-pad  S=R  A=L  Escape=Quit
 */

#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <string.h>
#include <dlfcn.h>
#include <unistd.h>
#include <signal.h>
#include <execinfo.h>

#include "global.h"
#include "gba/gba.h"
#include "main.h"
#include "gpu_regs.h"
#include "intro.h"
#include "palette.h"
#include "task.h"
#include "sprite.h"
#include "bg.h"
#include "dma3.h"
#include "play_time.h"
#include "malloc.h"
#include "load_save.h"
#include "main_menu.h"
#include "oak_speech.h"
#include "save.h"
#include "sound.h"
#include "m4a.h"
#include "link_rfu.h"
#include "quest_log.h"
#include "help_system.h"
#include "new_menu_helpers.h"
#include "save_failed_screen.h"
#include "host_sound_init.h"
#include "host_audio.h"

/* Declared in main.c (non-static) but no header */
extern void EnableVCountIntrAtLine150(void);
extern void SetNotInSaveFailedScreen(void);
#include "title_screen.h"
#include "host_memory.h"
#include "host_renderer.h"
#include "host_display.h"
#include "host_crt0.h"
#include "host_intro_stubs.h"
#include "host_frame_step.h"
#include "overworld.h"
#include "host_new_game_stubs.h"
#include "host_oak_speech_stubs.h"
#include "host_title_screen_stubs.h"

/* Patch functions generated by tools/script_assembler.py */
void HostPatchBattleScriptPointers(void);
void HostPatchEventScriptPointers(void);
void HostPatchFieldEffectScriptPointers(void);
void HostPatchBattleAIScriptPointers(void);
void HostPatchBattleAnimScriptPointers(void);

/* ── Interrupt handlers ────────────────────────────────────── */

/* Oak speech text externs removed — StringExpandPlaceholders now from upstream */

static FILE *sTraceFile;
static MainCallback sLastCallback1;
static MainCallback sLastCallback2;
static u32 sLastMainMenuInitCalls;
static u32 sLastStartNewGameSceneCalls;
static u32 sLastNamingCalls;
static u32 sLastControlsGuidePage1Loads;
static u32 sLastControlsGuidePage2Loads;
static u32 sLastControlsGuidePage3Loads;
static u32 sLastPikachuIntroPage1Loads;
static u32 sLastPikachuIntroPage2Loads;
static u32 sLastPikachuIntroPage3Loads;
static u32 sLastWelcomePrints;
static u32 sLastThisWorldPrints;
static u32 sUniformFrameRunLength;
static u32 sLastUniformColor;
static bool8 sSnapshotRequested;
static char sSnapshotLabel[96];

#define MAX_SCRIPTED_INPUT_RANGES 256

struct ScriptedInputRange
{
    u32 startFrame;
    u32 endFrame;
    u16 pressedMask;
};

static struct ScriptedInputRange sScriptedInputRanges[MAX_SCRIPTED_INPUT_RANGES];
static u32 sScriptedInputRangeCount;
static bool8 sScriptedInputEnabled;

static void TraceLog(u32 frame, const char *message);

static u16 ParseInputToken(const char *token)
{
    if (strcmp(token, "A") == 0)
        return A_BUTTON;
    if (strcmp(token, "B") == 0)
        return B_BUTTON;
    if (strcmp(token, "SELECT") == 0)
        return SELECT_BUTTON;
    if (strcmp(token, "START") == 0)
        return START_BUTTON;
    if (strcmp(token, "RIGHT") == 0)
        return DPAD_RIGHT;
    if (strcmp(token, "LEFT") == 0)
        return DPAD_LEFT;
    if (strcmp(token, "UP") == 0)
        return DPAD_UP;
    if (strcmp(token, "DOWN") == 0)
        return DPAD_DOWN;
    if (strcmp(token, "R") == 0)
        return R_BUTTON;
    if (strcmp(token, "L") == 0)
        return L_BUTTON;
    if (strcmp(token, "NONE") == 0)
        return 0;
    return 0xFFFF;
}

static bool8 ParseInputMask(const char *maskText, u16 *outMask)
{
    char buffer[128];
    char *token;
    char *savePtr = NULL;
    u16 mask = 0;

    if (strncmp(maskText, "0x", 2) == 0 || strncmp(maskText, "0X", 2) == 0)
    {
        char *endPtr = NULL;
        unsigned long value = strtoul(maskText, &endPtr, 16);

        if (endPtr == NULL || *endPtr != '\0')
            return FALSE;
        *outMask = (u16)value;
        return TRUE;
    }

    snprintf(buffer, sizeof(buffer), "%.127s", maskText);
    token = strtok_r(buffer, "+|,", &savePtr);
    while (token != NULL)
    {
        u16 value = ParseInputToken(token);

        if (value == 0xFFFF)
            return FALSE;
        mask |= value;
        token = strtok_r(NULL, "+|,", &savePtr);
    }

    *outMask = mask;
    return TRUE;
}

static bool8 LoadScriptedInputFile(const char *path)
{
    FILE *file = fopen(path, "r");
    char line[256];
    u32 lineNumber = 0;

    if (file == NULL)
    {
        fprintf(stderr, "pfr_play: could not open input script %s\n", path);
        return FALSE;
    }

    sScriptedInputRangeCount = 0;
    while (fgets(line, sizeof(line), file) != NULL)
    {
        char *hash;
        char *startText;
        char *endText;
        char *maskText;
        char *savePtr = NULL;
        unsigned long startFrame;
        unsigned long endFrame;
        u16 mask;

        lineNumber++;
        hash = strchr(line, '#');
        if (hash != NULL)
            *hash = '\0';

        startText = strtok_r(line, " \t\r\n", &savePtr);
        if (startText == NULL)
            continue;
        endText = strtok_r(NULL, " \t\r\n", &savePtr);
        maskText = strtok_r(NULL, " \t\r\n", &savePtr);

        if (endText == NULL || maskText == NULL)
        {
            fprintf(stderr, "pfr_play: malformed input script line %u\n", lineNumber);
            fclose(file);
            return FALSE;
        }

        startFrame = strtoul(startText, NULL, 10);
        endFrame = strtoul(endText, NULL, 10);
        if (endFrame < startFrame)
        {
            fprintf(stderr, "pfr_play: invalid frame range on line %u\n", lineNumber);
            fclose(file);
            return FALSE;
        }

        if (!ParseInputMask(maskText, &mask))
        {
            fprintf(stderr, "pfr_play: invalid input mask on line %u: %s\n", lineNumber, maskText);
            fclose(file);
            return FALSE;
        }

        if (sScriptedInputRangeCount >= MAX_SCRIPTED_INPUT_RANGES)
        {
            fprintf(stderr, "pfr_play: too many scripted input ranges\n");
            fclose(file);
            return FALSE;
        }

        sScriptedInputRanges[sScriptedInputRangeCount].startFrame = (u32)startFrame;
        sScriptedInputRanges[sScriptedInputRangeCount].endFrame = (u32)endFrame;
        sScriptedInputRanges[sScriptedInputRangeCount].pressedMask = mask;
        sScriptedInputRangeCount++;
    }

    fclose(file);
    sScriptedInputEnabled = TRUE;
    return TRUE;
}

static void ApplyScriptedInput(u32 frame)
{
    u16 pressedMask = 0;
    u32 i;

    if (!sScriptedInputEnabled)
        return;

    for (i = 0; i < sScriptedInputRangeCount; i++)
    {
        if (frame >= sScriptedInputRanges[i].startFrame && frame <= sScriptedInputRanges[i].endFrame)
            pressedMask |= sScriptedInputRanges[i].pressedMask;
    }

    REG_KEYINPUT = KEYS_MASK & ~pressedMask;
}

static void RequestSnapshot(const char *label)
{
    snprintf(sSnapshotLabel, sizeof(sSnapshotLabel), "%.95s", label);
    sSnapshotRequested = TRUE;
}

static void SanitizeSnapshotLabel(char *label)
{
    size_t i;

    for (i = 0; label[i] != '\0'; i++)
    {
        char c = label[i];

        if (!((c >= 'a' && c <= 'z')
           || (c >= 'A' && c <= 'Z')
           || (c >= '0' && c <= '9')
           || c == '_' || c == '-'))
        {
            label[i] = '_';
        }
    }
}

static void DumpCurrentFramebuffer(u32 frame, const char *label)
{
    char safeLabel[96];
    char path[192];
    const u32 *fb = HostRendererGetFramebuffer();
    FILE *f;
    int i;

    snprintf(safeLabel, sizeof(safeLabel), "%s", label);
    SanitizeSnapshotLabel(safeLabel);
    snprintf(path, sizeof(path), "pfr_play_frames/%06u_%s.ppm", frame, safeLabel);

    f = fopen(path, "wb");
    if (f == NULL)
        return;

    fprintf(f, "P6\n%d %d\n255\n", GBA_SCREEN_WIDTH, GBA_SCREEN_HEIGHT);
    for (i = 0; i < GBA_SCREEN_WIDTH * GBA_SCREEN_HEIGHT; i++)
    {
        u32 pixel = fb[i];
        u8 rgb[3];

        rgb[0] = (pixel >> 16) & 0xFF;
        rgb[1] = (pixel >> 8) & 0xFF;
        rgb[2] = pixel & 0xFF;
        fwrite(rgb, 1, 3, f);
    }

    fclose(f);
}

static u32 CountNonZeroWords(const void *data, size_t size)
{
    const u32 *words = data;
    size_t count = size / sizeof(u32);
    u32 nonZero = 0;
    size_t i;

    for (i = 0; i < count; i++)
    {
        if (words[i] != 0)
            nonZero++;
    }

    return nonZero;
}

static void TraceGpuState(u32 frame, const char *label)
{
    char buffer[256];
    u16 dispcnt = GetGpuReg(REG_OFFSET_DISPCNT);
    u16 bg0cnt = GetGpuReg(REG_OFFSET_BG0CNT);
    u16 bg1cnt = GetGpuReg(REG_OFFSET_BG1CNT);
    u16 bg2cnt = GetGpuReg(REG_OFFSET_BG2CNT);
    u16 bg3cnt = GetGpuReg(REG_OFFSET_BG3CNT);
    u16 bldcnt = GetGpuReg(REG_OFFSET_BLDCNT);
    u16 bldalpha = GetGpuReg(REG_OFFSET_BLDALPHA);
    u16 bldy = GetGpuReg(REG_OFFSET_BLDY);
    u16 winin = GetGpuReg(REG_OFFSET_WININ);
    u16 winout = GetGpuReg(REG_OFFSET_WINOUT);
    u16 bg0hofs = GetGpuReg(REG_OFFSET_BG0HOFS);
    u16 bg0vofs = GetGpuReg(REG_OFFSET_BG0VOFS);
    u16 bg1hofs = GetGpuReg(REG_OFFSET_BG1HOFS);
    u16 bg1vofs = GetGpuReg(REG_OFFSET_BG1VOFS);
    u16 bg2hofs = GetGpuReg(REG_OFFSET_BG2HOFS);
    u16 bg2vofs = GetGpuReg(REG_OFFSET_BG2VOFS);
    u32 plttNonZero = CountNonZeroWords((const void *)PLTT, PLTT_SIZE);
    u32 vramNonZero = CountNonZeroWords((const void *)VRAM, VRAM_SIZE);
    u32 oamNonZero = CountNonZeroWords((const void *)OAM, OAM_SIZE);
    const u16 *pltt = (const u16 *)PLTT;

    snprintf(buffer, sizeof(buffer),
             "%s gpu DISPCNT=0x%04X BG0=0x%04X BG1=0x%04X BG2=0x%04X BG3=0x%04X BLDCNT=0x%04X BLDALPHA=0x%04X BLDY=0x%04X WININ=0x%04X WINOUT=0x%04X",
             label, dispcnt, bg0cnt, bg1cnt, bg2cnt, bg3cnt, bldcnt, bldalpha, bldy, winin, winout);
    TraceLog(frame, buffer);

    snprintf(buffer, sizeof(buffer),
             "%s scroll BG0=(%u,%u) BG1=(%u,%u) BG2=(%u,%u) PLTT[0..3]=%04X,%04X,%04X,%04X nonZeroWords pltt=%u vram=%u oam=%u",
             label,
             bg0hofs, bg0vofs,
             bg1hofs, bg1vofs,
             bg2hofs, bg2vofs,
             pltt[0], pltt[1], pltt[2], pltt[3],
             plttNonZero, vramNonZero, oamNonZero);
    TraceLog(frame, buffer);
}

static void TraceLog(u32 frame, const char *message)
{
    if (sTraceFile != NULL)
    {
        fprintf(sTraceFile, "[%06u] %s\n", frame, message);
        fflush(sTraceFile);
    }
    fprintf(stderr, "[%06u] %s\n", frame, message);
}

/* ---- ELF symbol table lookup for callback tracing ---- */

struct SymEntry {
    uintptr_t addr;
    const char *name;
};

static struct SymEntry *sSymTable = NULL;
static int sSymCount = 0;

static int SymEntryCmp(const void *a, const void *b)
{
    uintptr_t aa = ((const struct SymEntry *)a)->addr;
    uintptr_t bb = ((const struct SymEntry *)b)->addr;
    return (aa > bb) - (aa < bb);
}

/* Build a sorted symbol table from `nm /proc/self/exe` at startup.
 * This captures ALL symbols including static (local) functions,
 * so every callback pointer resolves to a human-readable name. */
/* Use libc allocators directly — the game overrides malloc with its
 * own heap allocator that operates on gHeap, which isn't set up yet
 * when InitSymbolTable runs (and would corrupt the game heap). */
extern void *__libc_malloc(size_t);
extern void *__libc_realloc(void *, size_t);
extern void __libc_free(void *);

static char *sys_strdup(const char *s)
{
    size_t len = strlen(s) + 1;
    char *d = __libc_malloc(len);
    if (d) memcpy(d, s, len);
    return d;
}

static void InitSymbolTable(void)
{
    FILE *fp;
    char line[512];
    int capacity = 4096;

    sSymTable = __libc_malloc(capacity * sizeof(struct SymEntry));
    sSymCount = 0;
    if (!sSymTable)
        return;

    /* readlink /proc/self/exe to get the actual binary path,
     * then run nm on it to get all symbols including static ones. */
    char exe_path[1024];
    ssize_t len = readlink("/proc/self/exe", exe_path, sizeof(exe_path) - 1);
    if (len <= 0) return;
    exe_path[len] = 0;
    char cmd[1200];
    snprintf(cmd, sizeof(cmd), "nm -n %s 2>/dev/null", exe_path);
    fp = popen(cmd, "r");
    if (!fp) { __libc_free(sSymTable); sSymTable = NULL; return; }

    while (fgets(line, sizeof(line), fp))
    {
        uintptr_t addr;
        char type;
        char name[256];
        if (sscanf(line, "%lx %c %255s", &addr, &type, name) != 3)
            continue;
        if (type != 't' && type != 'T')
            continue;
        if (sSymCount >= capacity) {
            capacity *= 2;
            sSymTable = __libc_realloc(sSymTable, capacity * sizeof(struct SymEntry));
            if (!sSymTable) { sSymCount = 0; pclose(fp); return; }
        }
        sSymTable[sSymCount].addr = addr;
        sSymTable[sSymCount].name = sys_strdup(name);
        sSymCount++;
    }
    pclose(fp);
    qsort(sSymTable, sSymCount, sizeof(struct SymEntry), SymEntryCmp);
}

static const char *CallbackName(MainCallback callback)
{
    static char addr_buf[64];

    if (callback == NULL)
        return "NULL";

    /* Binary search the symbol table for an exact match */
    uintptr_t target = (uintptr_t)callback;
    int lo = 0, hi = sSymCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (sSymTable[mid].addr == target)
            return sSymTable[mid].name;
        else if (sSymTable[mid].addr < target)
            lo = mid + 1;
        else
            hi = mid - 1;
    }

    snprintf(addr_buf, sizeof(addr_buf), "0x%lx",
             (unsigned long)(uintptr_t)callback);
    return addr_buf;
}

/* OakPlaceholderName removed — StringExpandPlaceholders now from upstream */

static void TraceCallbackChange(u32 frame, const char *label, MainCallback callback)
{
    char buffer[160];

    snprintf(buffer, sizeof(buffer), "%s -> %s (%p)", label, CallbackName(callback), (void *)callback);
    TraceLog(frame, buffer);
    RequestSnapshot(buffer);
}

static void TraceInput(u32 frame)
{
    char buffer[128];

    if (gMain.newKeys == 0)
        return;

    snprintf(buffer, sizeof(buffer),
             "input newKeys=0x%04X heldKeys=0x%04X callback2=%s",
             gMain.newKeys,
             gMain.heldKeys,
             CallbackName(gMain.callback2));
    TraceLog(frame, buffer);
}

static void TraceMilestones(u32 frame)
{
    char buffer[160];

    if (gMain.callback1 != sLastCallback1)
    {
        sLastCallback1 = gMain.callback1;
        TraceCallbackChange(frame, "callback1", gMain.callback1);
    }

    if (gMain.callback2 != sLastCallback2)
    {
        sLastCallback2 = gMain.callback2;
        TraceCallbackChange(frame, "callback2", gMain.callback2);
    }

    if (gHostTitleStubCB2InitMainMenuCalls != sLastMainMenuInitCalls)
    {
        sLastMainMenuInitCalls = gHostTitleStubCB2InitMainMenuCalls;
        snprintf(buffer, sizeof(buffer), "main menu init calls=%u", sLastMainMenuInitCalls);
        TraceLog(frame, buffer);
        RequestSnapshot("main_menu_init");
    }

    if (gHostTitleStubStartNewGameSceneCalls != sLastStartNewGameSceneCalls)
    {
        sLastStartNewGameSceneCalls = gHostTitleStubStartNewGameSceneCalls;
        snprintf(buffer, sizeof(buffer), "StartNewGameScene calls=%u", sLastStartNewGameSceneCalls);
        TraceLog(frame, buffer);
        RequestSnapshot("start_new_game_scene");
    }

    if (gHostOakSpeechControlsGuidePage1Loads != sLastControlsGuidePage1Loads)
    {
        sLastControlsGuidePage1Loads = gHostOakSpeechControlsGuidePage1Loads;
        TraceLog(frame, "Oak controls guide page 1 reached");
        RequestSnapshot("oak_controls_page_1");
    }
    if (gHostOakSpeechControlsGuidePage2Loads != sLastControlsGuidePage2Loads)
    {
        sLastControlsGuidePage2Loads = gHostOakSpeechControlsGuidePage2Loads;
        TraceLog(frame, "Oak controls guide page 2 reached");
        RequestSnapshot("oak_controls_page_2");
    }
    if (gHostOakSpeechControlsGuidePage3Loads != sLastControlsGuidePage3Loads)
    {
        sLastControlsGuidePage3Loads = gHostOakSpeechControlsGuidePage3Loads;
        TraceLog(frame, "Oak controls guide page 3 reached");
        RequestSnapshot("oak_controls_page_3");
    }
    if (gHostOakSpeechPikachuIntroPage1Loads != sLastPikachuIntroPage1Loads)
    {
        sLastPikachuIntroPage1Loads = gHostOakSpeechPikachuIntroPage1Loads;
        TraceLog(frame, "Oak Pikachu intro page 1 reached");
        RequestSnapshot("oak_pikachu_intro_1");
    }
    if (gHostOakSpeechPikachuIntroPage2Loads != sLastPikachuIntroPage2Loads)
    {
        sLastPikachuIntroPage2Loads = gHostOakSpeechPikachuIntroPage2Loads;
        TraceLog(frame, "Oak Pikachu intro page 2 reached");
        RequestSnapshot("oak_pikachu_intro_2");
    }
    if (gHostOakSpeechPikachuIntroPage3Loads != sLastPikachuIntroPage3Loads)
    {
        sLastPikachuIntroPage3Loads = gHostOakSpeechPikachuIntroPage3Loads;
        TraceLog(frame, "Oak Pikachu intro page 3 reached");
        RequestSnapshot("oak_pikachu_intro_3");
    }
    if (gHostOakSpeechWelcomeToTheWorldPrints != sLastWelcomePrints)
    {
        sLastWelcomePrints = gHostOakSpeechWelcomeToTheWorldPrints;
        TraceLog(frame, "Oak welcome message printed");
        RequestSnapshot("oak_welcome_message");
    }
    if (gHostOakSpeechThisWorldPrints != sLastThisWorldPrints)
    {
        sLastThisWorldPrints = gHostOakSpeechThisWorldPrints;
        TraceLog(frame, "Oak 'This world' message printed");
        RequestSnapshot("oak_this_world_message");
    }

    /* StringExpandPlaceholders and CB2_NewGame now from upstream —
       placeholder source tracking removed */

    if (gHostOakSpeechDoNamingScreenCalls != sLastNamingCalls)
    {
        sLastNamingCalls = gHostOakSpeechDoNamingScreenCalls;
        snprintf(buffer, sizeof(buffer), "Oak naming screen calls=%u", sLastNamingCalls);
        TraceLog(frame, buffer);
        RequestSnapshot("oak_naming_screen");
    }
}

static void TraceFramebufferUniformity(u32 frame)
{
    const u32 *framebuffer = HostRendererGetFramebuffer();
    u32 first = framebuffer[0];
    u32 sameCount = 1;
    int i;

    for (i = 64; i < GBA_SCREEN_WIDTH * GBA_SCREEN_HEIGHT; i += 64)
    {
        if (framebuffer[i] == first)
            sameCount++;
    }

    if (sameCount >= 590)
    {
        if (sUniformFrameRunLength == 0 || sLastUniformColor != first)
        {
            sUniformFrameRunLength = 1;
            sLastUniformColor = first;
        }
        else
        {
            sUniformFrameRunLength++;
        }

        if (sUniformFrameRunLength == 120)
        {
            char buffer[160];

            snprintf(buffer, sizeof(buffer),
                     "framebuffer nearly uniform for 120 frames, color=0x%08X callback2=%s",
                     sLastUniformColor,
                     CallbackName(gMain.callback2));
            TraceLog(frame, buffer);
            RequestSnapshot("uniform_frame_warning");
        }
    }
    else
    {
        sUniformFrameRunLength = 0;
    }
}

static void PlayVBlankHandler(void)
{
    extern u16 Random(void);
    /* Match real VBlankIntr from main.c as closely as possible.
     * Skipped: RfuVSync/LinkVSync (no wireless/link on native).
     * Skipped: m4aSoundMain (hangs without DMA hardware). */

    if (gMain.vblankCounter1)
        (*gMain.vblankCounter1)++;

    if (gMain.vblankCallback)
        gMain.vblankCallback();

#ifdef PFR_DIAG
    {
        static u32 sDiagVBlankCount = 0;
        if (gMain.vblankCallback != NULL && sDiagVBlankCount % 60 == 0)
            fprintf(stderr, "[PFR_DIAG] PlayVBlankHandler: vblankCallback=%p frame=%u\n",
                    (void *)gMain.vblankCallback, gMain.vblankCounter2);
        sDiagVBlankCount++;
    }
#endif

    gMain.vblankCounter2++;

    CopyBufferedValuesToGpuRegs();
    ProcessDma3Requests();

    HostAudioMixAndPush();

    Random();

    INTR_CHECK |= INTR_FLAG_VBLANK;
    gMain.intrCheck |= INTR_FLAG_VBLANK;
}

static void PlayHBlankHandler(void)
{
    if (gMain.hblankCallback)
        gMain.hblankCallback();
    gMain.intrCheck |= INTR_FLAG_HBLANK;
}

static void IntrDummy(void) { }

/* ── Key reading (mirrors main.c's static ReadKeys) ────────── */

/* Not exported in main.h but defined in main.c, set by InitKeys() */
extern u16 gKeyRepeatContinueDelay;

static void PlayReadKeys(void)
{
    u16 keyInput = REG_KEYINPUT ^ KEYS_MASK;

    gMain.newKeysRaw = keyInput & ~gMain.heldKeysRaw;
    gMain.newKeys = gMain.newKeysRaw;
    gMain.newAndRepeatedKeys = gMain.newKeysRaw;

    if (keyInput != 0 && gMain.heldKeys == keyInput)
    {
        gMain.keyRepeatCounter--;
        if (gMain.keyRepeatCounter == 0)
        {
            gMain.newAndRepeatedKeys = keyInput;
            gMain.keyRepeatCounter = gKeyRepeatContinueDelay;
        }
    }
    else
    {
        gMain.keyRepeatCounter = gKeyRepeatStartDelay;
    }

    gMain.heldKeysRaw = keyInput;
    gMain.heldKeys = gMain.heldKeysRaw;

    if (gSaveBlock2Ptr->optionsButtonMode == OPTIONS_BUTTON_MODE_L_EQUALS_A)
    {
        if (JOY_NEW(L_BUTTON))
            gMain.newKeys |= A_BUTTON;
        if (JOY_HELD(L_BUTTON))
            gMain.heldKeys |= A_BUTTON;
    }

    if (JOY_NEW(gMain.watchedKeysMask))
        gMain.watchedKeysPressed = TRUE;
}

/* ── Frame simulation ──────────────────────────────────────── */

struct PlayFrameContext
{
    u32 frame;
};

static void PlayFrameLogic(void *userdata)
{
    const struct PlayFrameContext *ctx = userdata;
    u32 frame = ctx->frame;

    ApplyScriptedInput(frame);
    PlayReadKeys();
    TraceInput(frame);
    TraceMilestones(frame);

    if (gMain.callback1)
        gMain.callback1();
    if (gMain.callback2)
        gMain.callback2();

    PlayTimeCounter_Update();
    MapMusicMain();
}

static void StepFrame(void)
{
    static u32 frame;
    struct PlayFrameContext ctx = { .frame = frame };

    HostFrameStepRun(PlayFrameLogic, &ctx);

    frame++;
}

/* ── Main ──────────────────────────────────────────────────── */

static void crash_handler(int sig)
{
    void *frames[32];
    int n = backtrace(frames, 32);
    fprintf(stderr, "\n=== CRASH: signal %d ===\n", sig);
    backtrace_symbols_fd(frames, n, STDERR_FILENO);
    _exit(128 + sig);
}

int main(int argc, char *argv[])
{
    signal(SIGSEGV, crash_handler);
    signal(SIGABRT, crash_handler);

    int i;
    const char *scriptPath = NULL;

    if (argc > 1)
        scriptPath = argv[1];

    /* Initialize host subsystems */
    HostMemoryInit();
    HostRendererInit();

    if (!HostDisplayInit())
    {
        fprintf(stderr, "pfr_play: Failed to initialize display (SDL2 required)\n");
        return 1;
    }

    /* Boot chain */
    HostCrt0Init();
    REG_KEYINPUT = KEYS_MASK; /* all keys released */

    /* ── AgbMain initialization sequence ── */

    InitGpuRegManager();

    /* Interrupt dispatch table */
    for (i = 0; i < 14; i++)
        gIntrTable[i] = IntrDummy;
    gIntrTable[3] = PlayHBlankHandler;
    gIntrTable[4] = PlayVBlankHandler;

    REG_IME = 1;
    REG_IE |= INTR_FLAG_VBLANK;

    InitKeys();

    /* Full native sound init: sets up SOUND_INFO_PTR, all SoundInfo fields,
     * music players, and cry players — without DMA/timer hardware writes. */
    HostNativeSoundInit();
    HostAudioInit();

    EnableVCountIntrAtLine150();
    /* InitRFU() skipped: spins on rfu_waitREQComplete() waiting for
     * wireless adapter hardware response. No wireless adapter on native.
     * Single-player gameplay does not use RFU. */
    CheckForFlashMemory();

    /* InitMainCallbacks is static in main.c; replicate inline: */
    gMain.vblankCounter1 = 0;
    gMain.vblankCounter2 = 0;
    gMain.callback1 = NULL;
    gMain.callback2 = NULL;
    gMain.vblankCallback = NULL;
    gMain.state = 0;
    gSaveBlock2Ptr = &gSaveBlock2;
    gSaveBlock1Ptr = &gSaveBlock1;
    gSaveBlock2.encryptionKey = 0;
    gQuestLogPlaybackState = QL_PLAYBACK_STATE_STOPPED;

    InitMapMusic();
    ClearDma3Requests();
    ResetBgs();
    InitHeap(gHeap, HEAP_SIZE);
    SetDefaultFontsPointer();

    gSoftResetDisabled = FALSE;
    gHelpSystemEnabled = FALSE;
    SetNotInSaveFailedScreen();

    gHostIntroStubLoadGameSaveResult = SAVE_STATUS_EMPTY;
    HostNewGameStubReset();
    HostOakSpeechStubReset();

    /* Patch 32-bit LE pointer fields in generated script bytecode arrays.
     * Must run before any game code that reads script pointers. */
    HostPatchBattleScriptPointers();
    HostPatchEventScriptPointers();
    HostPatchFieldEffectScriptPointers();
    HostPatchBattleAIScriptPointers();
    HostPatchBattleAnimScriptPointers();

    HostIntroStubReset();
    HostTitleScreenStubReset();
    mkdir("pfr_play_frames", 0775);
    sTraceFile = fopen("pfr_play_trace.log", "w");
    if (sTraceFile != NULL)
        setvbuf(sTraceFile, NULL, _IOLBF, 0);
    sLastCallback1 = (MainCallback)(uintptr_t)-1;
    sLastCallback2 = (MainCallback)(uintptr_t)-1;
    sLastUniformColor = 0;
    sUniformFrameRunLength = 0;
    sScriptedInputEnabled = FALSE;
    sScriptedInputRangeCount = 0;
    InitSymbolTable();
    TraceLog(0, "pfr_play trace started");

    if (scriptPath != NULL)
    {
        char buffer[160];

        if (!LoadScriptedInputFile(scriptPath))
            return 1;
        snprintf(buffer, sizeof(buffer),
                 "loaded scripted input file %s with %u ranges",
                 scriptPath,
                 sScriptedInputRangeCount);
        TraceLog(0, buffer);
    }

    {
        extern void CB2_InitCopyrightScreenAfterBootup(void);
        SetMainCallback2(CB2_InitCopyrightScreenAfterBootup);
    }

    /* ── Main loop ── */

    for (;;)
    {
        StepFrame();

        /* HostDisplayPresent: render → present → poll input → vsync pacing.
         * Returns FALSE on ESC / window close. */
        if (!HostDisplayPresent())
            break;

        if (sSnapshotRequested)
        {
            TraceGpuState(HostDisplayGetFrameCount(), sSnapshotLabel);
            DumpCurrentFramebuffer(HostDisplayGetFrameCount(), sSnapshotLabel);
            sSnapshotRequested = FALSE;
        }

        /* Periodic snapshots at stable frames for debugging */
        {
            u32 fc = HostDisplayGetFrameCount();
            if (fc == 2000 || fc == 13100 || fc == 13200 || fc == 13300 ||
                fc == 13500 || fc == 14000 || fc == 14500 || fc == 15000 ||
                fc == 16000 || fc == 17000 || fc == 18000 || fc == 20000)
            {
                char label[32];
                snprintf(label, sizeof(label), "periodic_%u", fc);
                DumpCurrentFramebuffer(fc, label);
            }
        }

        TraceFramebufferUniformity(HostDisplayGetFrameCount());
    }

    HostAudioShutdown();
    HostDisplayDestroy();
    if (sTraceFile != NULL)
        fclose(sTraceFile);
    return 0;
}
