/* Auto-generated by extend_gen.py — DO NOT EDIT MANUALLY */
#ifndef PFR_NATIVE_TILESET_DATA_H
#define PFR_NATIVE_TILESET_DATA_H

#include <stdint.h>
#include <stddef.h>

/* GBA metatile rendering:
 * Each metatile is 16x16 pixels, composed of 8 tiles (8x8 each).
 * Layout: 2 layers (bottom, top) x 4 quadrants (TL, TR, BL, BR).
 * metatile_entries[metatile_id * 8 + i] is a u16:
 *   bits 0-9:  tile_index into tile_pixels
 *   bit  10:   horizontal flip
 *   bit  11:   vertical flip
 *   bits 12-15: palette index (0-15)
 * tile_pixels: 4bpp indexed, 32 bytes per 8x8 tile.
 * palettes: 16 palettes of 16 colors each, GBA RGB555 format.
 */

typedef struct {
    const uint8_t  *tile_pixels;      /* 4bpp tile data (32 bytes per tile) */
    uint16_t        tile_count;        /* number of 8x8 tiles */
    const uint16_t *palettes;          /* 16 palettes * 16 colors, RGB555 */
    const uint16_t *metatile_entries;  /* 8 entries per metatile */
    uint16_t        metatile_count;    /* number of metatiles */
} PfrNativeTileset;

/* Tileset IDs */
#define PFR_TILESET_NULL 0
#define PFR_TILESET_BERRYFOREST 1
#define PFR_TILESET_BIKESHOP 2
#define PFR_TILESET_BUILDING 3
#define PFR_TILESET_BURGLEDHOUSE 4
#define PFR_TILESET_CABLECLUB 5
#define PFR_TILESET_CAVE 6
#define PFR_TILESET_CELADONCITY 7
#define PFR_TILESET_CELADONGYM 8
#define PFR_TILESET_CERULEANCAVE 9
#define PFR_TILESET_CERULEANCITY 10
#define PFR_TILESET_CERULEANGYM 11
#define PFR_TILESET_CINNABARGYM 12
#define PFR_TILESET_CINNABARISLAND 13
#define PFR_TILESET_CONDOMINIUMS 14
#define PFR_TILESET_DEPARTMENTSTORE 15
#define PFR_TILESET_DIGLETTSCAVE 16
#define PFR_TILESET_DUMMY1 17
#define PFR_TILESET_FANCLUBDAYCARE 18
#define PFR_TILESET_FUCHSIACITY 19
#define PFR_TILESET_FUCHSIAGYM 20
#define PFR_TILESET_GAMECORNER 21
#define PFR_TILESET_GENERAL 22
#define PFR_TILESET_GENERICBUILDING1 23
#define PFR_TILESET_GENERICBUILDING2 24
#define PFR_TILESET_HALLOFFAME 25
#define PFR_TILESET_HOENNBUILDING 26
#define PFR_TILESET_INDIGOPLATEAU 27
#define PFR_TILESET_ISLANDHARBOR 28
#define PFR_TILESET_LAB 29
#define PFR_TILESET_LAVENDERTOWN 30
#define PFR_TILESET_MART 31
#define PFR_TILESET_MTEMBER 32
#define PFR_TILESET_MUSEUM 33
#define PFR_TILESET_NAVELROCK 34
#define PFR_TILESET_PALLETTOWN 35
#define PFR_TILESET_PEWTERCITY 36
#define PFR_TILESET_PEWTERGYM 37
#define PFR_TILESET_POKEMONCENTER 38
#define PFR_TILESET_POKEMONLEAGUE 39
#define PFR_TILESET_POKEMONMANSION 40
#define PFR_TILESET_POKEMONTOWER 41
#define PFR_TILESET_POWERPLANT 42
#define PFR_TILESET_RESTAURANTHOTEL 43
#define PFR_TILESET_ROCKTUNNEL 44
#define PFR_TILESET_SSANNE 45
#define PFR_TILESET_SAFARIZONEBUILDING 46
#define PFR_TILESET_SAFFRONCITY 47
#define PFR_TILESET_SAFFRONGYM 48
#define PFR_TILESET_SCHOOL 49
#define PFR_TILESET_SEACOTTAGE 50
#define PFR_TILESET_SEAFOAMISLANDS 51
#define PFR_TILESET_SEVIIISLANDS123 52
#define PFR_TILESET_SEVIIISLANDS45 53
#define PFR_TILESET_SEVIIISLANDS67 54
#define PFR_TILESET_SILPHCO 55
#define PFR_TILESET_TANOBYRUINS 56
#define PFR_TILESET_TRAINERTOWER 57
#define PFR_TILESET_UNDERGROUNDPATH 58
#define PFR_TILESET_VERMILIONCITY 59
#define PFR_TILESET_VERMILIONGYM 60
#define PFR_TILESET_VIRIDIANCITY 61
#define PFR_TILESET_VIRIDIANFOREST 62
#define PFR_TILESET_VIRIDIANGYM 63
#define PFR_TILESET_COUNT 64

extern const uint16_t gPfrNativeTilesetCount;
extern const PfrNativeTileset gPfrNativeTilesets[];

#endif /* PFR_NATIVE_TILESET_DATA_H */